Repository OpenLoco/OpenLoco, pull requests merged in 2019-02, with the labels that each got.

#266 Decompile GUI initialisation
  src/openloco/audio/audio.cpp
  src/openloco/graphics/colour.cpp
  src/openloco/graphics/colours.h
  src/openloco/graphics/gfx.cpp
  src/openloco/graphics/gfx.h
  src/openloco/input.cpp
  src/openloco/input.h
  src/openloco/input/mouse_input.cpp
  src/openloco/interop/hooks.cpp
  src/openloco/localisation/string_ids.h
  src/openloco/localisation/stringmgr.h
  src/openloco/openloco.cpp
  src/openloco/openloco.h
  src/openloco/ui/WindowManager.cpp
  src/openloco/ui/WindowManager.h
  src/openloco/viewportmgr.cpp
  src/openloco/viewportmgr.h
Labels: pending review

#280 Build application bundle for macOS
  .gitignore
  .travis.yml
  CMakeLists.txt
  distribution/macos/AppIcon.iconset/Contents.json
  distribution/macos/Info.plist.in
  src/openloco/environment.cpp
  src/openloco/environment.h
  src/openloco/localisation/languagefiles.cpp
  src/openloco/localisation/languages.cpp
  src/openloco/platform/platform.h
  src/openloco/platform/platform.macos.mm
Labels: macOS (OS)

#284 Fetch more of the repository history for non clang-format builds
  .travis.yml
Labels: build
