Repository OpenLoco/OpenLoco, pull requests merged in 2020-08, with the labels that each got.

#578 Fix #573: Crash caused by opening Road construction window
  src/openloco/windows/construction/Common.cpp
Labels: changelog

#577 Vehicle Superclass V2
  src/openloco/things/CreateVehicle.cpp
  src/openloco/things/vehicle.cpp
  src/openloco/things/vehicle.h
  src/openloco/windows/CompanyWindow.cpp
  src/openloco/windows/News/News.cpp
  src/openloco/windows/map.cpp
Labels: refactor

#569 Optionally disable AI companies entirely
  CHANGELOG.md
  data/language/en-GB.yml
  src/openloco/companymgr.cpp
  src/openloco/config.cpp
  src/openloco/config.h
  src/openloco/localisation/string_ids.h
  src/openloco/windows/options.cpp
Labels: changelog, discussion
