Repository OpenLoco/OpenLoco, pull requests merged in 2020-07, with the labels that each got.

#523 Construction: holdable build and remove buttons
  CHANGELOG.md
  src/openloco/windows/construction/Common.cpp
  src/openloco/windows/construction/ConstructionTab.cpp
Labels: squash merge

#530 Fix industry production not starting up under some conditions
  CHANGELOG.md
  src/openloco/industry.cpp
Labels: changelog, squash merge

#505 Implement tutorial routines
  CHANGELOG.md
  src/openloco/config.h
  src/openloco/environment.h
  src/openloco/input.h
  src/openloco/input/keyboard.cpp
  src/openloco/input/mouse_input.cpp
  src/openloco/interop/hooks.cpp
  src/openloco/localisation/string_ids.h
  src/openloco/openloco.cpp
  src/openloco/scenario.cpp
  src/openloco/scenario.h
  src/openloco/tutorial.cpp
  src/openloco/tutorial.h
  src/openloco/ui.cpp
  src/openloco/ui.h
  src/openloco/windows/title_menu.cpp
  src/openloco/windows/tooltip.cpp
Labels: changelog

#525 Vehicle refactor
  src/openloco/audio/audio.cpp
  src/openloco/audio/audio.h
  src/openloco/audio/vehicle_channel.cpp
  src/openloco/company.cpp
  src/openloco/interop/hooks.cpp
  src/openloco/things/CreateVehicle.cpp
  src/openloco/things/thingmgr.cpp
  src/openloco/things/thingmgr.h
  src/openloco/things/vehicle.cpp
  src/openloco/things/vehicle.h
  src/openloco/windows/CompanyWindow.cpp
  src/openloco/windows/toolbar_top.cpp
Labels: refactor

#551 Fix #491: Station/city names disappear on save.
  CHANGELOG.md
  src/openloco/viewportmgr.cpp
  src/openloco/viewportmgr.h
Labels: changelog

#553 Close #540: Widen options window for German, Polish strings
  src/openloco/windows/options.cpp
Labels: squash merge

#560 Fix #558: Station catchment area not invalidating map properly
  src/openloco/map/tile.h
  src/openloco/map/tile_loop.hpp
  src/openloco/windows/stationwnd.cpp
Labels: squash merge
