Repository OpenLoco/OpenLoco, pull requests merged in 2020-12, with the labels that each got.

#678 Implement construction rotate shortcut
  src/OpenLoco/Input.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending improvement

#682 Reorg thing so that base has access to more
  src/OpenLoco/Audio/VehicleChannel.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Things/CreateVehicle.cpp
  src/OpenLoco/Things/Misc.cpp
  src/OpenLoco/Things/Misc.h
  src/OpenLoco/Things/Thing.cpp
  src/OpenLoco/Things/Thing.h
  src/OpenLoco/Things/Vehicle.cpp
  src/OpenLoco/Things/Vehicle.h
  src/OpenLoco/ViewportManager.cpp
  src/OpenLoco/ViewportManager.h
  src/OpenLoco/Window.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#683 Reorg thing2
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Things/CreateVehicle.cpp
  src/OpenLoco/Things/ThingManager.h
  src/OpenLoco/Things/Vehicle.cpp
  src/OpenLoco/Things/Vehicle.h
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
Labels: pending review

#669 Get map pos 2
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Station.h
  src/OpenLoco/Town.cpp
  src/OpenLoco/Town.h
  src/OpenLoco/Types.hpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/ViewportManager.cpp
Labels: pending review

#684 Reorg thing3
  src/OpenLoco/Things/Thing.h
  src/OpenLoco/Things/ThingManager.cpp
  src/OpenLoco/Things/ThingManager.h
Labels: squash merge

#681 Implement PaintSession::generate
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Window.cpp
Labels: pending review
