Repository OpenLoco/OpenLoco, pull requests merged in 2021-07, with the labels that each got.

#984 Station rename command
  CHANGELOG.md
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/RenameStation.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/StationManager.cpp
  src/OpenLoco/StationManager.h
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog, squash merge

#1028 Implement colour picker dropdowns
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/Ui/Dropdown.cpp
  src/OpenLoco/Ui/Dropdown.h
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TownList.cpp
Labels: pending review

#1029 Implement ChangeCompanyColour game command
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
  src/OpenLoco/GameCommands/ChangeCompanyColour.cpp
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#1043 CompanyWindow Link up implemented function
  src/OpenLoco/Windows/CompanyWindow.cpp
Labels: pending review

#1044 Refactor and fix headquarter placement
  CHANGELOG.md
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/Windows/CompanyWindow.cpp
Labels: changelog, testing required
