Repository OpenLoco/OpenLoco, pull requests merged in 2021-09, with the labels that each got.

#1122 Further cleanup of the browse window
  src/OpenLoco/Game.cpp
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Platform/Platform.Windows.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/PromptOkCancelWindow.cpp
Labels: pending review, testing required

#1138 Fix #1127: Crash during vehicle renewal cheat
  CHANGELOG.md
  src/OpenLoco/GameCommands/Cheat.cpp
Labels: changelog

#1130 Implement remove construction ghosts
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/Construction.h
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/Windows/Construction/SignalTab.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
  src/OpenLoco/Windows/StationWindow.cpp
Labels: pending review

#1117 Paint tile2
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintTile.cpp
Labels: pending review

#1141 Implement serialization of keyboard shortcuts
  CHANGELOG.md
  data/language/de-DE.yml
  data/language/en-GB.yml
  data/language/en-US.yml
  data/language/es-ES.yml
  data/language/fr-FR.yml
  data/language/it-IT.yml
  data/language/ja-JP.yml
  data/language/ko-KR.yml
  data/language/nl-NL.yml
  data/language/pl-PL.yml
  data/language/pt-BR.yml
  data/language/ru-RU.yml
  data/language/sk-SK.yml
  data/language/zh-CN.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/ConfigConvert.hpp
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/Input/ShortcutManager.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Ui.cpp
  src/OpenLoco/Windows/EditKeyboardShortcut.cpp
  src/OpenLoco/Windows/KeyboardShortcuts.cpp
Labels: pending review

#1144 Fix: Options window spawns behind title logo
  CHANGELOG.md
  src/OpenLoco/Windows/Options.cpp
Labels: pending review

#1149 Use strong types for IndustryId
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/RenameIndustry.cpp
  src/OpenLoco/Industry.cpp
  src/OpenLoco/Industry.h
  src/OpenLoco/IndustryManager.cpp
  src/OpenLoco/IndustryManager.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Station.cpp
  src/OpenLoco/Station.h
  src/OpenLoco/Types.hpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/News/News.cpp
Labels: pending review

#1153 Fix: Options window spawns behind title logo
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/TitleLogo.cpp
Labels: pending review

#1165 Fix #1162. Incorrect signal side placement.
  CHANGELOG.md
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Ui/Cursor.h
  src/OpenLoco/Windows/Construction/SignalTab.cpp
Labels: changelog

#1171 Don't zero out the z coordinate on load
  CHANGELOG.md
  src/OpenLoco/Entities/Entity.cpp
  src/OpenLoco/Entities/EntityManager.cpp
  src/OpenLoco/Entities/EntityManager.h
Labels: changelog

#1173 Fix turnaround not being selectable on right hand drive scenarios
  CHANGELOG.md
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
Labels: changelog

#1176 Fix headquarters ghost destroying buildings
  CHANGELOG.md
  CONTRIBUTORS.MD
  src/OpenLoco/Windows/CompanyWindow.cpp
Labels: changelog

#1177 Label further gamestate
  src/OpenLoco/GameState.h
  src/OpenLoco/S5/S5.h
Labels: changelog

#1174 Rework routing to add handle and label fields
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Routing.h
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#1175 Add track sub position data
  src/OpenLoco/SubpositionData.cpp
  src/OpenLoco/SubpositionData.h
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#1156 Use gamestate to get mult factors
  src/OpenLoco/Economy/Economy.cpp
Labels: pending review

#1133 Signal Element Paint
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Objects/TrainSignalObject.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintSignal.cpp
  src/OpenLoco/Paint/PaintSignal.h
  src/OpenLoco/Paint/PaintTile.cpp
  src/OpenLoco/Windows/TileInspector.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review
