Repository OpenLoco/OpenLoco, pull requests merged in 2021-06, with the labels that each got.

#993 Retry hook installation
  CHANGELOG.md
  src/OpenLoco/Interop/Hook.cpp
  src/OpenLoco/Interop/Interop.cpp
Labels: changelog

#996 Clarify availability of release builds and need for compilation
  README.md
Labels: pending review

#1006 Add breakpad to MSVC builds
  .github/workflows/ci.yml
  CHANGELOG.md
  openloco.common.props
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Platform/Crash.cpp
  src/OpenLoco/Platform/Crash.h
  src/OpenLoco/Platform/Platform.Posix.cpp
  src/OpenLoco/Platform/Platform.Windows.cpp
  src/OpenLoco/Platform/Platform.h
  src/OpenLoco/openloco.vcxproj
Labels: pending improvement

#533 Create a safe itererable wrapper for loco arrays
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/Core/LocoFixedVector.hpp
  src/OpenLoco/GameCommands/Cheat.cpp
  src/OpenLoco/IndustryManager.cpp
  src/OpenLoco/IndustryManager.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Interop/Interop.hpp
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/StationManager.cpp
  src/OpenLoco/StationManager.h
  src/OpenLoco/Town.cpp
  src/OpenLoco/TownManager.cpp
  src/OpenLoco/TownManager.h
  src/OpenLoco/Ui/Dropdown.cpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/Windows/StationList.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/openloco.vcxproj
Labels: refactor

#997 Allow filtering the vehicle list by station
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/VehicleList.cpp
Labels: changelog

#1012 Widget refactorings, turned draw functions into normal member functions.
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Widget.h
Labels: squash merge
