Repository OpenLoco/OpenLoco, pull requests merged in 2021-02, with the labels that each got.

#670 Start implementing viewport interaction item_left
  src/OpenLoco/Input.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Localisation/FormatArguments.hpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Map/Tile.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Station.cpp
  src/OpenLoco/Station.h
  src/OpenLoco/Things/Vehicle.cpp
  src/OpenLoco/Things/Vehicle.h
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/MapToolTip.cpp
  src/OpenLoco/Windows/StationList.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#718 Paintsetup 7: Vehicle Body
  src/OpenLoco/Objects/VehicleObject.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintVehicle.cpp
  src/OpenLoco/Things/CreateVehicle.cpp
  src/OpenLoco/Things/Vehicle.cpp
  src/OpenLoco/Things/Vehicle.h
Labels: pending review

#719 Implement 0x00440325 - paintMiscEntity
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Objects/ObjectManager.h
  src/OpenLoco/Objects/SteamObject.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintEntity.cpp
  src/OpenLoco/Paint/PaintMiscEntity.cpp
  src/OpenLoco/Paint/PaintMiscEntity.h
  src/OpenLoco/Things/Misc.cpp
  src/OpenLoco/Things/Misc.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/openloco.vcxproj
Labels: squash merge, testing required

#738 Vehicle update2 Part 1: Water Update
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Station.h
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#761 Fix #744. Z fighting issue caused by unhappy renderer
  CHANGELOG.md
  src/OpenLoco/Drawing/SoftwareDrawingEngine.cpp
  src/OpenLoco/Ui.h
Labels: changelog

#702 Implement some of the map generator
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Map/MapGenerator.cpp
  src/OpenLoco/Map/MapGenerator.h
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Map/TileManager.cpp
  src/OpenLoco/Map/TileManager.h
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Scenario.h
  src/OpenLoco/Title.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/LandscapeGeneration.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#748 Add ability to clone a vehicle
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/GameCommands.cpp
  src/OpenLoco/GameCommands.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Vehicles/CloneVehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#760 Feature: allow main viewport to follow an entity
  data/language/en-GB.yml
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/Vehicle.cpp
Labels: changelog, feature

#762 Dedicated buttons for local/express mode
  CHANGELOG.md
  data/language/de-DE.yml
  data/language/en-GB.yml
  data/language/en-US.yml
  data/language/es-ES.yml
  data/language/fr-FR.yml
  data/language/it-IT.yml
  data/language/ja-JP.yml
  data/language/ko-KR.yml
  data/language/nl-NL.yml
  data/language/pl-PL.yml
  data/language/pt-BR.yml
  data/language/ru-RU.yml
  data/language/sk-SK.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/Vehicle.cpp
Labels: changelog

#785 Fix #294. Crash when setting company name twice
  CHANGELOG.md
  src/OpenLoco/GameCommands.h
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/ScenarioOptions.cpp
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/Windows/TextInputWindow.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: changelog

#575 Implement editor bottom toolbar
  src/OpenLoco/EditorController.cpp
  src/OpenLoco/EditorController.h
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/Gui.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Ui/WindowType.h
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/ToolbarBottomEditor.cpp
  src/OpenLoco/openloco.vcxproj
Labels: squash merge

#783 More compact syntax for game command table
  src/OpenLoco/GameCommands.cpp
  src/OpenLoco/GameCommands.h
  src/OpenLoco/Ui.cpp
Labels: pending review, squash merge

#807 Fix speed based vehicle animations such as hydrofoils
  CHANGELOG.md
  src/OpenLoco/Vehicles/VehicleBody.cpp
Labels: changelog
