Repository OpenLoco/OpenLoco, pull requests merged in 2021-03, with the labels that each got.

#796 Add sandbox mode to the game
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/GameCommands.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Objects/InterfaceSkinObject.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/OpenLoco.h
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/Map.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
  src/OpenLoco/Windows/ToolbarTopCommon.h
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: changelog

#362 Implement inflation-related functions
  CHANGELOG.md
  src/OpenLoco/Economy.cpp
  src/OpenLoco/Economy.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Scenario.h
Labels: changelog, pending review

#824 Implement the RenameIndustry game command
  src/OpenLoco/GameCommands.cpp
  src/OpenLoco/GameCommands.h
  src/OpenLoco/GameCommands/RenameIndustry.cpp
  src/OpenLoco/Industry.h
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#825 Implement the RenameTown game command
  CHANGELOG.md
  src/OpenLoco/GameCommands.cpp
  src/OpenLoco/GameCommands.h
  src/OpenLoco/GameCommands/RenameTown.cpp
  src/OpenLoco/Town.cpp
  src/OpenLoco/Town.h
  src/OpenLoco/TownManager.cpp
  src/OpenLoco/Types.hpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#809 Use simplified vector implementations with resolution translation
  CHANGELOG.md
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Map/Map.hpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Math/Vector.hpp
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintEntity.h
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/Things/ThingManager.h
  src/OpenLoco/Types.hpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Viewport.hpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog, pending rebase

#839 Fix #838: Escape key doesn't work in confirmation windows
  CHANGELOG.md
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/PromptOkCancelWindow.cpp
Labels: squash merge

#835 Vehicle Update 2 Part 2e: Implement airportGetApronTransitionTarget
  src/OpenLoco/Objects/AirportObject.h
  src/OpenLoco/Station.h
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#834 Vehicle Update 2 Part 3a: Start the regular movement code
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#840 Vehicle Update 2 Part 3e: Implement landTryBeginUnloading and landLoadingUpdate
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#836 Vehicle Update 2 Part 3c: Implements sub_4A8CB6
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#837 Vehicle Update 2 Part 3d: Implements sub_4A8C81 part of manual vehicle control
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#844 Fix monthly town update
  CHANGELOG.md
  src/OpenLoco/Town.h
  src/OpenLoco/TownManager.cpp
Labels: changelog, pending review

#848 Implement progress bar window
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Map/MapGenerator.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/OpenLoco.h
  src/OpenLoco/ProgressBar.cpp
  src/OpenLoco/ProgressBar.h
  src/OpenLoco/Ui/ProgressBar.cpp
  src/OpenLoco/Ui/ProgressBar.h
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/ProgressBar.cpp
  src/OpenLoco/openloco.vcxproj
Labels: squash merge

#841 Implement PromptBrowseWindow::handleInput
  CHANGELOG.md
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
Labels: changelog

#850 Add simple FPS counter
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Drawing/FPSCounter.cpp
  src/OpenLoco/Drawing/FPSCounter.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Ui.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/openloco.vcxproj
Labels: squash merge

#853 Implement variable frame updating
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/OpenLoco.h
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Widget.h
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/Options.cpp
Labels: changelog

#810 Use map_pos3 over Loc16
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/Audio.h
  src/OpenLoco/Location.hpp
  src/OpenLoco/Things/Misc.cpp
  src/OpenLoco/Things/Misc.h
  src/OpenLoco/Things/Thing.cpp
  src/OpenLoco/Things/Thing.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Viewport.cpp
  src/OpenLoco/Viewport.hpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/TownWindow.cpp
Labels: pending review

#860 Fix capacity string showing incorrect data
  CHANGELOG.md
  src/OpenLoco/Objects/VehicleObject.cpp
Labels: pending review

#849 Implement tutorial footer window
  src/OpenLoco/Gui.cpp
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Tutorial.cpp
  src/OpenLoco/Tutorial.h
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/Tutorial.cpp
  src/OpenLoco/openloco.vcxproj
Labels: squash merge

#831 Implement a basic tile inspector
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Map/TileManager.cpp
  src/OpenLoco/Map/TileManager.h
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Ui/WindowType.h
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TileInspector.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#868 Remove a thing
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/MusicChannel.h
  src/OpenLoco/Audio/VehicleChannel.cpp
  src/OpenLoco/Audio/VehicleChannel.h
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/Entities/Entity.cpp
  src/OpenLoco/Entities/Entity.h
  src/OpenLoco/Entities/EntityManager.cpp
  src/OpenLoco/Entities/EntityManager.h
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/Entities/Misc.h
  src/OpenLoco/GameCommands.h
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintEntity.cpp
  src/OpenLoco/Paint/PaintMiscEntity.cpp
  src/OpenLoco/Paint/PaintMiscEntity.h
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Things/ThingManager.h
  src/OpenLoco/Types.hpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Vehicles/CloneVehicle.cpp
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/OrderSkip.cpp
  src/OpenLoco/Vehicles/RenameVehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/ViewportManager.cpp
  src/OpenLoco/ViewportManager.h
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/DragVehiclePart.cpp
  src/OpenLoco/Windows/Map.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
  src/OpenLoco/Windows/ToolbarTopCommon.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#869 Implement create money effect
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/Entities/EntityManager.cpp
  src/OpenLoco/Entities/EntityManager.h
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/Entities/Misc.h
  src/OpenLoco/GameCommands.cpp
  src/OpenLoco/Viewport.cpp
  src/OpenLoco/Viewport.hpp
Labels: pending review
