Repository OpenLoco/OpenLoco, pull requests merged in 2021-04, with the labels that each got.

#889 Cleanup isPlaced instances; move generateCargoTotalString
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#878 Implement the vehicle list window
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Objects/InterfaceSkinObject.h
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/VehicleList.cpp
Labels: pending review

#885 Fix #884: UTF8 problems with path in Windows
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
Labels: changelog, pending review

#917 Fix ships not marking stations as occupied
  CHANGELOG.md
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#906 Implement entity move to list
  src/OpenLoco/Entities/Entity.h
  src/OpenLoco/Entities/EntityManager.cpp
  src/OpenLoco/Entities/EntityManager.h
Labels: pending review

#927 Fix not all industries showing up in industry foundation tab
  CHANGELOG.md
  src/OpenLoco/Windows/IndustryList.cpp
Labels: changelog, pending review

#910 Implement cheats window
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/Currency.h
  src/OpenLoco/GameCommands/Cheat.cpp
  src/OpenLoco/GameCommands/Cheat.h
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Town.cpp
  src/OpenLoco/Town.h
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Ui/WindowType.h
  src/OpenLoco/Windows/Cheats.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog, squash merge

#926 Vehicle pickup game command
  src/OpenLoco/Audio/Audio.h
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/VehiclePickup.cpp
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/openloco.vcxproj
Labels: squash merge

#925 Fix #914. Actually fix correctly this time.
  CHANGELOG.md
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: changelog

#907 Fix #857: Remember last saved location in configuration variable
  CHANGELOG.md
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Environment.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
Labels: changelog, squash merge

#918 Vehicle cargo2: sub_4BA7C7
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#947 Fix panel heights in several windows
  src/OpenLoco/Windows/Construction/Construction.h
  src/OpenLoco/Windows/Map.cpp
  src/OpenLoco/Windows/TileInspector.cpp
Labels: pending review

#950 Move all windows into Ui::Windows namespace
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/GameCommands/TogglePause.cpp
  src/OpenLoco/Gui.cpp
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/About.cpp
  src/OpenLoco/Windows/AboutMusic.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/EditKeyboardShortcut.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/KeyboardShortcuts.cpp
  src/OpenLoco/Windows/Main.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/News/News.h
  src/OpenLoco/Windows/News/Ticker.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/PromptOkCancelWindow.cpp
  src/OpenLoco/Windows/StationList.cpp
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TileInspector.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/Windows/TitleExit.cpp
  src/OpenLoco/Windows/TitleLogo.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/TitleOptions.cpp
  src/OpenLoco/Windows/TitleVersion.cpp
  src/OpenLoco/Windows/ToolTip.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopCommon.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#923 Entity Tweening
  CHANGELOG.md
  src/OpenLoco/Entities/EntityManager.cpp
  src/OpenLoco/Entities/EntityTweener.cpp
  src/OpenLoco/Entities/EntityTweener.h
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Ui.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#954 Implement updateSnowLine
  src/OpenLoco/Map/MapGenerator.cpp
  src/OpenLoco/Objects/ClimateObject.h
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Objects/ObjectManager.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Scenario.h
Labels: pending review

#951 Refactor construction window
  src/OpenLoco/Graphics/Colour.h
  src/OpenLoco/Objects/RoadStationObject.cpp
  src/OpenLoco/Objects/RoadStationObject.h
  src/OpenLoco/Objects/TrainStationObject.cpp
  src/OpenLoco/Objects/TrainStationObject.h
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
Labels: pending review
