Repository OpenLoco/OpenLoco, pull requests merged in 2022-08, with the labels that each got.

#1600 Hook malloc and free a bit higher up in the call stack. Fixes running on Apple M1.
  CHANGELOG.md
  src/OpenLoco/Interop/Hooks.cpp
Labels: changelog

#1603 Undo change in Gfx::drawStringLeftWrapped
  src/OpenLoco/Graphics/Gfx.cpp
Labels: pending review

#1602 Add <array> include for gcc 12
  src/OpenLoco/Graphics/Gfx.h
Labels: pending review

#1606 inintialise bgm audio channel volume when playing a song (#729)
  CHANGELOG.md
  src/OpenLoco/Audio/Audio.cpp
Labels: changelog

#1609 _musicCurrentChannel variable isn't used for anything meaningful
  src/OpenLoco/Audio/Audio.cpp
Labels: pending review, refactor

#1616 Fix #1613. Crash when viewing Build Trains window
  CHANGELOG.md
  src/OpenLoco/Graphics/Gfx.cpp
Labels: pending review

#1617 Fix 1614: Crash on pickup of none existent vehicles
  CHANGELOG.md
  src/OpenLoco/GameCommands/VehiclePickup.cpp
Labels: pending review

#1615 Fix #1612. Ambient audio no longer playing
  CHANGELOG.md
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/Channel.h
Labels: pending review, changelog

#1618 Rename widget type wt_5 to slider
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: squash merge

#1620 Split PaletteMap out of Gfx.cpp/Gfx.h
  src/OpenLoco/Drawing/DrawSpriteHelper.hpp
  src/OpenLoco/Graphics/Colour.cpp
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Graphics/PaletteMap.cpp
  src/OpenLoco/Graphics/PaletteMap.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review, refactor
