Repository OpenLoco/OpenLoco, pull requests merged in 2022-03, with the labels that each got.

#1290 Map Gen Surface Styleing
  src/OpenLoco/Map/MapGenerator.cpp
  src/OpenLoco/Map/MapGenerator.h
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Map/TileLoop.hpp
  src/OpenLoco/Objects/LandObject.h
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Windows/LandscapeGeneration.cpp
Labels: pending review

#1358 Misc fixes from static analysis
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Objects/VehicleObject.h
  src/OpenLoco/Ui/ScrollView.cpp
  src/OpenLoco/Vehicles/Orders.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/MusicSelection.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
Labels: pending improvement

#1360 Apply codestyle for Window struct in Window.h
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Station.cpp
  src/OpenLoco/StationManager.cpp
  src/OpenLoco/Ui/ScrollView.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/ViewportManager.cpp
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/About.cpp
  src/OpenLoco/Windows/AboutMusic.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/Cheats.cpp
  src/OpenLoco/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/Windows/EditKeyboardShortcut.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/KeyboardShortcuts.cpp
  src/OpenLoco/Windows/LandscapeGeneration.cpp
  src/OpenLoco/Windows/LandscapeGenerationConfirm.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/MusicSelection.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/PromptOkCancelWindow.cpp
  src/OpenLoco/Windows/PromptSaveWindow.cpp
  src/OpenLoco/Windows/ScenarioOptions.cpp
  src/OpenLoco/Windows/ScenarioSelect.cpp
  src/OpenLoco/Windows/StationList.cpp
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TextInputWindow.cpp
  src/OpenLoco/Windows/TileInspector.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/Windows/TitleExit.cpp
  src/OpenLoco/Windows/TitleLogo.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/TitleOptions.cpp
  src/OpenLoco/Windows/ToolbarBottomEditor.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
Labels: pending review, refactor

#1329 Object load
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Objects/Object.h
  src/OpenLoco/Objects/ObjectManager.cpp
Labels: pending review

#1337 Fix removeElement removeTree code
  src/OpenLoco/GameCommands/RemoveTree.cpp
  src/OpenLoco/GameCommands/RemoveWall.cpp
  src/OpenLoco/Map/TileManager.cpp
Labels: pending review

#1367 Remove redundant if statement
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: refactor

#1366 Refactor out out parameters from getPart
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Ui/ScrollView.cpp
  src/OpenLoco/Ui/ScrollView.h
  src/OpenLoco/Windows/Vehicle.cpp
Labels: refactor

#1347 Introduce OpenAL-soft
  .github/workflows/ci.yml
  CHANGELOG.md
  CMakeLists.txt
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/Audio.h
  src/OpenLoco/Audio/Channel.cpp
  src/OpenLoco/Audio/Channel.h
  src/OpenLoco/Audio/MusicChannel.cpp
  src/OpenLoco/Audio/MusicChannel.h
  src/OpenLoco/Audio/OpenAL.cpp
  src/OpenLoco/Audio/OpenAL.h
  src/OpenLoco/Audio/VehicleChannel.cpp
  src/OpenLoco/Audio/VehicleChannel.h
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#1369 Remove references to SDL2_mixer
  CHANGELOG.md
  CMakeLists.txt
  README.md
  cmake/FindSDL2_mixer.cmake
Labels: pending review

#1354 Option to display obsolete or future proposed vehicles
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/Cheats.cpp
Labels: feature, changelog, cheat

#1378 add changelog for v22.03.1+
  CHANGELOG.md
Labels: pending review

#1379 Format year correctly in set-date cheat
  CHANGELOG.md
  data/language/en-GB.yml
Labels: enhancement, pending review, changelog

#1385 Move sound attributes to base channel
  src/OpenLoco/Audio/Channel.cpp
  src/OpenLoco/Audio/Channel.h
  src/OpenLoco/Audio/VehicleChannel.cpp
  src/OpenLoco/Audio/VehicleChannel.h
Labels: pending review, refactor

#1384 Fix tile loop not including the last tile
  src/OpenLoco/Map/TileLoop.hpp
Labels: pending review

#1388 Fix delete key not working in text input
  CHANGELOG.md
  src/OpenLoco/Ui/TextInput.cpp
Labels: pending review, changelog

#1389 Fixes signed/unsigned formatting bug on total vehicle power
  CHANGELOG.md
  src/OpenLoco/Localisation/StringManager.cpp
Labels: changelog

#1332 Implement Industry::updateProducedCargo
  src/OpenLoco/Industry.cpp
  src/OpenLoco/Industry.h
  src/OpenLoco/IndustryManager.cpp
  src/OpenLoco/IndustryManager.h
  src/OpenLoco/Map/TileManager.cpp
Labels: pending review

#1336 Implement companyThinkFunc2 functions
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
Labels: pending review

#1396 Fix divergence from previous PR
  src/OpenLoco/Industry.cpp
Labels: pending review

#1395 Implement a company think 1 function
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
Labels: pending review

#1405 codestyle changes for WindowEventList
  src/OpenLoco/Ui/Dropdown.cpp
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/About.cpp
  src/OpenLoco/Windows/AboutMusic.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/Cheats.cpp
  src/OpenLoco/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/Windows/Construction/SignalTab.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
  src/OpenLoco/Windows/DragVehiclePart.cpp
  src/OpenLoco/Windows/EditKeyboardShortcut.cpp
  src/OpenLoco/Windows/Error.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/KeyboardShortcuts.cpp
  src/OpenLoco/Windows/LandscapeGeneration.cpp
  src/OpenLoco/Windows/LandscapeGenerationConfirm.cpp
  src/OpenLoco/Windows/MapToolTip.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/MusicSelection.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/News/Ticker.cpp
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/Windows/ProgressBar.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/PromptOkCancelWindow.cpp
  src/OpenLoco/Windows/PromptSaveWindow.cpp
  src/OpenLoco/Windows/ScenarioOptions.cpp
  src/OpenLoco/Windows/ScenarioSelect.cpp
  src/OpenLoco/Windows/StationList.cpp
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TextInputWindow.cpp
  src/OpenLoco/Windows/TileInspector.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/Windows/TitleExit.cpp
  src/OpenLoco/Windows/TitleLogo.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/TitleOptions.cpp
  src/OpenLoco/Windows/ToolTip.cpp
  src/OpenLoco/Windows/ToolbarBottomEditor.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Tutorial.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
Labels: refactor

#1406 codestyle changes for WindowFlags
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/Title.cpp
  src/OpenLoco/Ui/Dropdown.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/DragVehiclePart.cpp
  src/OpenLoco/Windows/Error.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/Windows/Main.cpp
  src/OpenLoco/Windows/MapToolTip.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/Windows/ProgressBar.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/PromptOkCancelWindow.cpp
  src/OpenLoco/Windows/PromptSaveWindow.cpp
  src/OpenLoco/Windows/ScenarioSelect.cpp
  src/OpenLoco/Windows/StationList.cpp
  src/OpenLoco/Windows/StationWindow.cpp
  src/OpenLoco/Windows/TextInputWindow.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/Windows/TitleExit.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
  src/OpenLoco/Windows/TitleOptions.cpp
  src/OpenLoco/Windows/TitleVersion.cpp
  src/OpenLoco/Windows/ToolTip.cpp
  src/OpenLoco/Windows/ToolbarBottomEditor.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/TownWindow.cpp
  src/OpenLoco/Windows/Tutorial.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
Labels: refactor

#1399 Sort vehicles correctly in build vehicle window
  CHANGELOG.md
  src/OpenLoco/Windows/BuildVehicle.cpp
Labels: enhancement, pending review, changelog

#1410 apply codestyle to ScrollArea struct
  src/OpenLoco/Ui/ScrollView.cpp
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Window.h
Labels: pending review, refactor

#1380 #1316 build locked vehicles
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/Cheats.cpp
Labels: feature, pending review, changelog, cheat

#1411 fixes landscapes not saving in scenario editor
  CHANGELOG.md
  src/OpenLoco/Game.cpp
  src/OpenLoco/Game.h
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
Labels: enhancement, pending review, changelog

#1400 Make power conversion from imperial to metric match vanilla
  CHANGELOG.md
  src/OpenLoco/Localisation/StringManager.cpp
Labels: enhancement, pending review, changelog

#1370 Ambient sound update
  src/OpenLoco/Audio/Audio.cpp
Labels: pending review

#1333 Split up object functions
  src/OpenLoco/Objects/CargoObject.cpp
  src/OpenLoco/Objects/CargoObject.h
  src/OpenLoco/Objects/CurrencyObject.cpp
  src/OpenLoco/Objects/CurrencyObject.h
  src/OpenLoco/Objects/InterfaceSkinObject.cpp
  src/OpenLoco/Objects/InterfaceSkinObject.h
  src/OpenLoco/Objects/LandObject.cpp
  src/OpenLoco/Objects/LandObject.h
  src/OpenLoco/Objects/LevelCrossingObject.cpp
  src/OpenLoco/Objects/LevelCrossingObject.h
  src/OpenLoco/Objects/Object.h
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Objects/ObjectManager.h
  src/OpenLoco/Objects/RockObject.cpp
  src/OpenLoco/Objects/RockObject.h
  src/OpenLoco/Objects/SoundObject.cpp
  src/OpenLoco/Objects/SoundObject.h
  src/OpenLoco/Objects/SteamObject.cpp
  src/OpenLoco/Objects/SteamObject.h
  src/OpenLoco/Objects/TownNamesObject.cpp
  src/OpenLoco/Objects/TownNamesObject.h
  src/OpenLoco/Objects/TrainSignalObject.cpp
  src/OpenLoco/Objects/TrainSignalObject.h
  src/OpenLoco/Objects/WallObject.cpp
  src/OpenLoco/Objects/WallObject.h
  src/OpenLoco/Objects/WaterObject.cpp
  src/OpenLoco/Objects/WaterObject.h
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#1352 Implement getVehicleSoundParameters
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/Audio.h
  src/OpenLoco/Audio/VehicleChannel.cpp
Labels: pending review

#1409 Switch to std::array's and stdx::span for trackData
  src/OpenLoco/Map/Track/TrackData.cpp
  src/OpenLoco/Map/Track/TrackData.h
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
Labels: pending review

#1382 MessageManager
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
  src/OpenLoco/GameState.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Message.cpp
  src/OpenLoco/Message.h
  src/OpenLoco/MessageManager.cpp
  src/OpenLoco/MessageManager.h
  src/OpenLoco/Objects/CargoObject.h
  src/OpenLoco/Objects/IndustryObject.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/News/Ticker.cpp
Labels: pending review

#1419 apply code style to LocoConfig struct
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Localisation/StringManager.cpp
  src/OpenLoco/MessageManager.cpp
  src/OpenLoco/Paint/PaintEntity.cpp
  src/OpenLoco/Ui.cpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/ViewportManager.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/MusicSelection.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/ScenarioSelect.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
Labels: refactor

#1421 apply code style to NewConfig struct
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Environment.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Tutorial.cpp
  src/OpenLoco/Ui.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Window.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
Labels: pending review, refactor

#1420 apply code style to Display struct
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Ui.cpp
  src/OpenLoco/Windows/Options.cpp
Labels: pending review, refactor
