Repository OpenLoco/OpenLoco, pull requests merged in 2022-11, with the labels that each got.

#1709 Implement viewport left/right rotate
  src/OpenLoco/Window.cpp
  src/OpenLoco/Window.h
Labels: reverse-engineering

#1700 Implement Paint Industry
  src/OpenLoco/Graphics/Colour.cpp
  src/OpenLoco/Graphics/Colour.h
  src/OpenLoco/Map/IndustryElement.h
  src/OpenLoco/Map/Tile.cpp
  src/OpenLoco/Objects/BuildingObject.h
  src/OpenLoco/Objects/IndustryObject.cpp
  src/OpenLoco/Objects/IndustryObject.h
  src/OpenLoco/Objects/ScaffoldingObject.cpp
  src/OpenLoco/Objects/ScaffoldingObject.h
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintIndustry.cpp
  src/OpenLoco/Paint/PaintIndustry.h
  src/OpenLoco/Paint/PaintTile.cpp
  src/OpenLoco/openloco.vcxproj
Labels: reverse-engineering

#1696 allow the user to view the .dat file name in object selection menu
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
Labels: enhancement, changelog

#1719 Implement WindowManager::updateDaily and ObjectManager::reloadAll
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/src/Windows/ToolTip.cpp
  src/OpenLoco/src/Windows/ToolbarTopAlt.cpp
Labels: reverse-engineering

#1720 Implement Temporary Object Loading/freeing. Cleanup/fix object loading.
  CHANGELOG.md
  src/OpenLoco/src/Objects/ObjectIndex.cpp
  src/OpenLoco/src/Objects/ObjectIndex.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: reverse-engineering

#1716 Implement the two industry animation functions
  src/OpenLoco/src/Map/AnimationManager.cpp
  src/OpenLoco/src/Map/IndustryElement.cpp
  src/OpenLoco/src/Map/IndustryElement.h
Labels: reverse-engineering

#1722 Fix #1676, #1702. Scenario list crash/hang on new scenarios
  CHANGELOG.md
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/Windows/ScenarioSelect.cpp
Labels: changelog

#1721 Implement Object Loading String table
  CHANGELOG.md
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Interop/Hooks.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Localisation/StringManager.cpp
  src/OpenLoco/src/Localisation/StringManager.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/Objects/ObjectStringTable.cpp
  src/OpenLoco/src/Objects/ObjectStringTable.h
  src/OpenLoco/src/Windows/Options.cpp
Labels: pending review, changelog, reverse-engineering
