Repository OpenLoco/OpenLoco, pull requests merged in 2022-05, with the labels that each got.

#1484 Hold shift when placing a vehicle to start it immediately
  CHANGELOG.md
  src/OpenLoco/Windows/Vehicle.cpp
Labels: enhancement, pending rebase, changelog

#1493 split ScenarioObjective::Objective into 2 parts, so part of it can be reused in S5::Options
  src/OpenLoco/EditorController.cpp
  src/OpenLoco/GameState.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/ScenarioObjective.cpp
  src/OpenLoco/ScenarioObjective.h
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/TimePanel.cpp
Labels: refactor

#1496 Refactor to use types and cleanup RCT2 structs
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Ui/ViewportInteraction.cpp
Labels: refactor

#1495 Use quarter tile for track data
  src/OpenLoco/Map/QuarterTile.h
  src/OpenLoco/Map/Track/TrackData.cpp
  src/OpenLoco/Map/Track/TrackData.h
Labels: refactor

#1499 Reenable Tree wilt
  CHANGELOG.md
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Graphics/ImageId.h
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Paint/PaintTree.cpp
Labels: changelog

#1508 Fix time limit for scenarios being set incorrectly
  CHANGELOG.md
  src/OpenLoco/Scenario.cpp
Labels: pending review

#1513 Add option to toggle visibility of cash popups
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Paint/PaintMiscEntity.cpp
  src/OpenLoco/Windows/Options.cpp
Labels: pending review

#1512 reduce locoglobals for 0x0052622E
  src/OpenLoco/GameState.h
  src/OpenLoco/Objects/VehicleObject.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
Labels: refactor

#1514 reduce locoglobals - move 0x0112C876 (currentFontSpriteBase) into Gfx.h
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Ui/Dropdown.cpp
  src/OpenLoco/Ui/TextInput.cpp
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/Windows/Construction/Construction.h
  src/OpenLoco/Windows/Error.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/News/News.h
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/Windows/TextInputWindow.cpp
  src/OpenLoco/Windows/ToolTip.cpp
Labels: refactor

#1423 Implement further objFuncs
  src/OpenLoco/Objects/AirportObject.cpp
  src/OpenLoco/Objects/AirportObject.h
  src/OpenLoco/Objects/BridgeObject.cpp
  src/OpenLoco/Objects/BridgeObject.h
  src/OpenLoco/Objects/DockObject.cpp
  src/OpenLoco/Objects/DockObject.h
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Objects/RoadExtraObject.cpp
  src/OpenLoco/Objects/RoadExtraObject.h
  src/OpenLoco/Objects/RoadObject.cpp
  src/OpenLoco/Objects/RoadObject.h
  src/OpenLoco/Objects/RoadStationObject.cpp
  src/OpenLoco/Objects/RoadStationObject.h
  src/OpenLoco/Objects/StreetLightObject.cpp
  src/OpenLoco/Objects/StreetLightObject.h
  src/OpenLoco/Objects/TrackExtraObject.cpp
  src/OpenLoco/Objects/TrackExtraObject.h
  src/OpenLoco/Objects/TrackObject.cpp
  src/OpenLoco/Objects/TrackObject.h
  src/OpenLoco/Objects/TrainStationObject.cpp
  src/OpenLoco/Objects/TrainStationObject.h
  src/OpenLoco/Objects/TunnelObject.cpp
  src/OpenLoco/Objects/TunnelObject.h
  src/OpenLoco/Objects/VehicleObject.cpp
  src/OpenLoco/Objects/VehicleObject.h
Labels: pending review

#1477 Implement exhaust update
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/Entities/Misc.h
  src/OpenLoco/Objects/SteamObject.cpp
  src/OpenLoco/Objects/SteamObject.h
  src/OpenLoco/Objects/TrainStationObject.h
  src/OpenLoco/Paint/PaintMiscEntity.cpp
  src/OpenLoco/Vehicles/VehicleBody.cpp
Labels: pending review

#1511 Port over OpenRCT2 Draw sprite
  src/OpenLoco/Drawing/DrawSprite.cpp
  src/OpenLoco/Drawing/DrawSprite.h
  src/OpenLoco/Drawing/DrawSpriteBMP.hpp
  src/OpenLoco/Drawing/DrawSpriteHelper.hpp
  src/OpenLoco/Drawing/DrawSpriteRLE.hpp
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Graphics/ImageId.h
  src/OpenLoco/openloco.vcxproj
Labels: pending review
