Repository OpenLoco/OpenLoco, pull requests merged in 2022-10, with the labels that each got.

#1657 Raise filename length limit back to 200 chars
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
Labels: pending review

#1660 Move company records into a standalone structure
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyRecords.h
  src/OpenLoco/GameState.h
  src/OpenLoco/MessageManager.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Speed.hpp
  src/OpenLoco/Windows/CompanyList.cpp
  src/OpenLoco/openloco.vcxproj
Labels: refactor

#1658 Add writeLocoCall to interop
  src/OpenLoco/Interop/Hook.cpp
  src/OpenLoco/Interop/Interop.hpp
Labels: reverse-engineering

#1621 Industry Manager Functions 3
  src/OpenLoco/GameCommands/RemoveBuilding.cpp
  src/OpenLoco/IndustryManager.cpp
  src/OpenLoco/Map/BuildingTile.cpp
  src/OpenLoco/Map/TileManager.cpp
  src/OpenLoco/Map/TileManager.h
  src/OpenLoco/Objects/IndustryObject.h
  src/OpenLoco/TownManager.cpp
  src/OpenLoco/TownManager.h
  src/OpenLoco/Windows/IndustryList.cpp
Labels: reverse-engineering

#1656 Implement changeCompanyFace game command
  src/OpenLoco/GameCommands/ChangeCompanyFace.cpp
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/openloco.vcxproj
Labels: pending improvement, reverse-engineering

#1155 Add Windows CMake CI
  .github/workflows/ci.yml
  .gitignore
  CMakeLists.txt
  CMakeSettings.json
  vcpkg.json
Labels: build

#1666 Add giant screenshots
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Input.h
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Ui/Screenshot.cpp
  src/OpenLoco/Ui/Screenshot.h
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
Labels: changelog

#1643 Implement Industry::expandGrounds
  src/OpenLoco/Industry.cpp
  src/OpenLoco/Industry.h
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Map/TileManager.cpp
  src/OpenLoco/Map/TileManager.h
  src/OpenLoco/Objects/IndustryObject.cpp
  src/OpenLoco/Objects/IndustryObject.h
Labels: pending review, reverse-engineering

#1684 fix title music playing in scenario editor
  CHANGELOG.md
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
Labels: changelog

#1697 Rename free/get scenarioText
  src/OpenLoco/Objects/ObjectIndex.cpp
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Objects/ObjectManager.h
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
Labels: refactor

#1695 Use v4 images with updated cmake
  .github/workflows/ci.yml
  CMakeLists.txt
Labels: hacktoberfest-accepted

#1673 Remove specific interop utility string functions
  src/OpenLoco/Environment.cpp
  src/OpenLoco/Graphics/PaletteMap.cpp
  src/OpenLoco/Interop/Interop.hpp
  src/OpenLoco/Network/NetworkConnection.cpp
  src/OpenLoco/Objects/ObjectIndex.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/Windows/TitleMenu.cpp
Labels: refactor

#1642 Introduce locoStrlen and locoStrcpy to handle args
  DEVELOPMENTLOG.md
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Localisation/StringManager.cpp
  src/OpenLoco/Localisation/StringManager.h
  src/OpenLoco/Objects/VehicleObject.cpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: refactor

#1694 IndustryObject::drawIndustry
  src/OpenLoco/Objects/IndustryObject.cpp
  src/OpenLoco/Objects/IndustryObject.h
Labels: reverse-engineering

#1669 RemoveIndustry Game Command
  src/OpenLoco/GameCommands/ChangeLandMaterial.cpp
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/RemoveBuilding.cpp
  src/OpenLoco/GameCommands/RemoveIndustry.cpp
  src/OpenLoco/Industry.cpp
  src/OpenLoco/Industry.h
  src/OpenLoco/Map/MapGenerator.cpp
  src/OpenLoco/Map/SurfaceTile.cpp
  src/OpenLoco/Map/Tile.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Objects/IndustryObject.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Ui/WindowManager.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/IndustryWindow.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review, reverse-engineering
