Repository OpenLoco/OpenLoco, pull requests merged in 2022-06, with the labels that each got.

#1479 Implement updateConstruction (sub_49FD66)
  src/OpenLoco/Input.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Paint/PaintTile.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/Construction.h
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
Labels: pending review

#1528 Rename tree wilt to noise mask
  src/OpenLoco/Drawing/DrawSprite.cpp
  src/OpenLoco/Drawing/DrawSprite.h
  src/OpenLoco/Drawing/DrawSpriteBMP.hpp
  src/OpenLoco/Drawing/DrawSpriteHelper.hpp
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Graphics/ImageId.h
  src/OpenLoco/Graphics/ImageIds.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Paint/PaintTree.cpp
Labels: pending review

#1532 reduce locoglobals - remove 0x0113600C as it isn't used
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/Windows/Construction/SignalTab.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: refactor

#1540 Add visitor pattern for vehicles access
  src/OpenLoco/Company.cpp
  src/OpenLoco/GameCommands/Cheat.cpp
  src/OpenLoco/GameCommands/VehiclePickup.cpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/Vehicle2.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/MapWindow.cpp
Labels: pending review

#1543 Add vehicle car count to vehicle details window
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: enhancement, changelog

#1418 Add BitSet.hpp from OpenRCT2
  src/OpenLoco/Core/BitSet.hpp
  src/OpenLoco/Industry.cpp
  src/OpenLoco/Industry.h
  src/OpenLoco/openloco.vcxproj
Labels: pending review, refactor
