Repository OpenLoco/OpenLoco, pull requests merged in 2022-02, with the labels that each got.

#1310 adds game command for setting game speed, and adds keyboard shortcuts
  CHANGELOG.md
  CONTRIBUTORS.md
  data/language/en-GB.yml
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/SetGameSpeed.cpp
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/Input/ShortcutManager.h
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/OpenLoco.h
  src/OpenLoco/Title.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/openloco.vcxproj
Labels: changelog

#1327 Readd ability to run Intro
  CHANGELOG.md
  src/OpenLoco/CommandLine.cpp
  src/OpenLoco/CommandLine.h
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Intro.cpp
  src/OpenLoco/OpenLoco.cpp
Labels: changelog

#1330 Apply coding style to environment.
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/Audio.h
  src/OpenLoco/Config.cpp
  src/OpenLoco/Environment.cpp
  src/OpenLoco/Environment.h
  src/OpenLoco/Game.cpp
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Localisation/LanguageFiles.cpp
  src/OpenLoco/Localisation/Languages.cpp
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Title.cpp
  src/OpenLoco/Tutorial.cpp
Labels: pending review

#1331 Implement TileManager::initialise
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Map/TileManager.cpp
Labels: pending review

#1322 Fix vehicle capacity string having a leading space
  data/language/en-GB.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#1276 Change how the cargo enroute age is calculated
  CHANGELOG.md
  src/OpenLoco/Station.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: changelog

#1335 Implement enqueue/dequeue mouse button and refactor
  src/OpenLoco/Input.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Ui.cpp
Labels: pending review

#1340 Fix Remove Crash Vehicle Crash
  CHANGELOG.md
  src/OpenLoco/Windows/News/News.cpp
Labels: changelog

#1343 rename constants in Limits.h to k-prefix
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/Entities/EntityManager.cpp
  src/OpenLoco/GameState.h
  src/OpenLoco/IndustryManager.cpp
  src/OpenLoco/IndustryManager.h
  src/OpenLoco/Localisation/StringManager.cpp
  src/OpenLoco/Map/AnimationManager.cpp
  src/OpenLoco/Map/WaveManager.cpp
  src/OpenLoco/MessageManager.cpp
  src/OpenLoco/S5/Limits.h
  src/OpenLoco/S5/S5.h
  src/OpenLoco/StationManager.cpp
  src/OpenLoco/StationManager.h
  src/OpenLoco/TownManager.cpp
  src/OpenLoco/TownManager.h
  src/OpenLoco/Ui/Dropdown.cpp
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Orders.cpp
  src/OpenLoco/Vehicles/Routing.h
  src/OpenLoco/Windows/LandscapeGeneration.cpp
  src/OpenLoco/Windows/MapWindow.cpp
Labels: refactor

#1328 Fix multiple object loading bugs
  CHANGELOG.md
  src/OpenLoco/Interop/Interop.cpp
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/ObjectSelectionWindow.cpp
Labels: pending review, changelog

#1323 fixes divide-by-zero audio crash when really far in future
  CHANGELOG.md
  src/OpenLoco/Audio/Audio.cpp
Labels: bug, pending review, changelog

#1350 add vehicle obsolete date to build vehicles window
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/BuildVehicle.cpp
Labels: enhancement, discussion, changelog

#1302 Implement Company::getAvailableRailTracks
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
  src/OpenLoco/Objects/RoadObject.h
  src/OpenLoco/Windows/ToolbarTop.cpp
Labels: pending improvement

#1353 Add stub functions for vehicle updates
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/Vehicle1.cpp
  src/OpenLoco/Vehicles/Vehicle2.cpp
  src/OpenLoco/Vehicles/VehicleBogie.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#1338 Implement updateOwnerStatus game command
  src/OpenLoco/Company.h
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/UpdateOwnerStatus.cpp
  src/OpenLoco/openloco.vcxproj
Labels: testing required
