Repository OpenLoco/OpenLoco, pull requests merged in 2022-04, with the labels that each got.

#1431 Fix vehicle sound being -100dB
  src/OpenLoco/Audio/VehicleChannel.cpp
Labels: pending review

#1417 Add empty() and size() helper methods to FixedVector
  src/OpenLoco/Core/LocoFixedVector.hpp
Labels: pending review, refactor

#1434 Fix underflow in number of towns in scenario editor
  CHANGELOG.md
  src/OpenLoco/S5/Limits.h
  src/OpenLoco/Windows/LandscapeGeneration.cpp
Labels: enhancement, pending review, changelog

#1365 Implement ObjectManager::load from header
  src/OpenLoco/Economy/Economy.cpp
  src/OpenLoco/Map/Tile.cpp
  src/OpenLoco/Objects/ObjectManager.cpp
  src/OpenLoco/Objects/ObjectManager.h
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/ScenarioSelect.cpp
Labels: pending review

#1398 Implement Company::updateMonthlyHeadquarters
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/OpenLoco.cpp
Labels: pending review

#1402 Implement destructExplosion
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/Entities/Misc.h
  src/OpenLoco/Map/TileManager.cpp
Labels: pending review

#1445 Fix #1229 Reliability Cheat
  CHANGELOG.md
  src/OpenLoco/GameCommands/Cheat.cpp
Labels: pending review

#1449 correctly format autopay tooltip
  CHANGELOG.md
  data/language/en-GB.yml
Labels: pending review, changelog

#1450 fix misc stringids
  CHANGELOG.md
  src/OpenLoco/Localisation/StringIds.h
Labels: pending review, changelog

#1443 Change entitymanager to check types more
  CHANGELOG.md
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Company.cpp
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/Entities/Entity.h
  src/OpenLoco/Entities/EntityManager.h
  src/OpenLoco/Entities/EntityTweener.cpp
  src/OpenLoco/Entities/Misc.h
  src/OpenLoco/GameCommands/Cheat.cpp
  src/OpenLoco/Input/Keyboard.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/MessageManager.cpp
  src/OpenLoco/Paint/PaintEntity.cpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/RenameVehicle.cpp
  src/OpenLoco/Vehicles/Routing.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/News/News.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
Labels: pending review, changelog

#1428 reduce loco_globals - _scenarioTicks and scenarioTicks()
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/Map/WaveManager.cpp
  src/OpenLoco/Objects/LevelCrossingObject.cpp
  src/OpenLoco/Objects/TrainSignalObject.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/OpenLoco.h
  src/OpenLoco/ScenarioManager.cpp
  src/OpenLoco/ScenarioManager.h
  src/OpenLoco/StationManager.cpp
  src/OpenLoco/TownManager.cpp
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: refactor

#1368 Implement Bogie::update()
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleBogie.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
Labels: pending review

#1426 reduce loco_globals with S5::getOptions()
  src/OpenLoco/EditorController.cpp
  src/OpenLoco/Game.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Tutorial.cpp
Labels: pending review, refactor

#781 Implement editor controller
  src/OpenLoco/Core/LocoFixedVector.hpp
  src/OpenLoco/EditorController.cpp
  src/OpenLoco/Game.cpp
  src/OpenLoco/Game.h
  src/OpenLoco/GameState.h
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/Interop/Hooks.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Ui/WindowManager.cpp
  src/OpenLoco/Windows/Options.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
Labels: pending review

#1465 Fix height calc
  src/OpenLoco/Map/TileManager.cpp
Labels: pending review

#1455 Label reused imageId flag
  src/OpenLoco/Graphics/Colour.h
  src/OpenLoco/Widget.cpp
  src/OpenLoco/Widget.h
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review

#1467 Split up z step
  src/OpenLoco/Audio/Audio.cpp
  src/OpenLoco/Audio/VehicleChannel.cpp
  src/OpenLoco/Company.cpp
  src/OpenLoco/Company.h
  src/OpenLoco/Entities/Misc.cpp
  src/OpenLoco/GameCommands/GameCommands.h
  src/OpenLoco/GameCommands/RemoveTree.cpp
  src/OpenLoco/GameCommands/RemoveWall.cpp
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Map/BuildingTile.cpp
  src/OpenLoco/Map/Map.hpp
  src/OpenLoco/Map/RoadTile.cpp
  src/OpenLoco/Map/SurfaceTile.cpp
  src/OpenLoco/Map/Tile.h
  src/OpenLoco/Map/TileManager.cpp
  src/OpenLoco/Map/WaveManager.cpp
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/PaintSignal.cpp
  src/OpenLoco/Paint/PaintTile.cpp
  src/OpenLoco/Paint/PaintTree.cpp
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/Vehicles/Routing.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleTail.cpp
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/Windows/Construction/SignalTab.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/Vehicle.cpp
Labels: pending review, refactor

#1432 Paint Station
  src/OpenLoco/Graphics/Colour.h
  src/OpenLoco/Objects/CargoObject.h
  src/OpenLoco/Objects/TrainStationObject.cpp
  src/OpenLoco/Objects/TrainStationObject.h
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintStation.cpp
  src/OpenLoco/Paint/PaintStation.h
  src/OpenLoco/Paint/PaintTile.cpp
  src/OpenLoco/Station.cpp
  src/OpenLoco/Station.h
  src/OpenLoco/openloco.vcxproj
Labels: pending review

#1390 Implement various addToPlotList functions
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Paint/Paint.cpp
  src/OpenLoco/Paint/Paint.h
  src/OpenLoco/Paint/PaintMiscEntity.cpp
  src/OpenLoco/Paint/PaintSignal.cpp
  src/OpenLoco/Paint/PaintStation.cpp
  src/OpenLoco/Paint/PaintTree.cpp
  src/OpenLoco/Ui.h
  src/OpenLoco/Ui/ViewportInteraction.cpp
  src/OpenLoco/ViewportManager.cpp
Labels: pending review

#1459 Add option to invert right-mouse view panning
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/Config.cpp
  src/OpenLoco/Config.h
  src/OpenLoco/Input/MouseInput.cpp
  src/OpenLoco/Localisation/StringIds.h
  src/OpenLoco/Windows/Options.cpp
Labels: feature, changelog

#1470 renames var_2C to trackAndDirection where applicable
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Vehicles/Routing.cpp
  src/OpenLoco/Vehicles/Vehicle.cpp
  src/OpenLoco/Vehicles/Vehicle.h
  src/OpenLoco/Vehicles/VehicleBody.cpp
  src/OpenLoco/Vehicles/VehicleHead.cpp
  src/OpenLoco/Vehicles/VehicleTail.cpp
Labels: pending review, refactor

#1429 reduce locoglobals - _playerCompany
  src/OpenLoco/GameCommands/GameCommands.cpp
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/Construction.h
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
  src/OpenLoco/Windows/MapWindow.cpp
  src/OpenLoco/Windows/MessageWindow.cpp
  src/OpenLoco/Windows/News/Common.cpp
  src/OpenLoco/Windows/News/News.h
  src/OpenLoco/Windows/TerraForm.cpp
Labels: pending review, refactor

#1482 Reduce locoglobals lastgameoption
  src/OpenLoco/GameState.h
  src/OpenLoco/Input/ShortcutManager.cpp
  src/OpenLoco/LastGameOptionManager.cpp
  src/OpenLoco/LastGameOptionManager.h
  src/OpenLoco/Map/MapGenerator.cpp
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/S5/S5.h
  src/OpenLoco/Vehicles/CreateVehicle.cpp
  src/OpenLoco/Windows/BuildVehicle.cpp
  src/OpenLoco/Windows/Construction/Common.cpp
  src/OpenLoco/Windows/Construction/Construction.h
  src/OpenLoco/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/Windows/Construction/StationTab.cpp
  src/OpenLoco/Windows/IndustryList.cpp
  src/OpenLoco/Windows/LandscapeGeneration.cpp
  src/OpenLoco/Windows/TerraForm.cpp
  src/OpenLoco/Windows/ToolbarTop.cpp
  src/OpenLoco/Windows/ToolbarTopAlt.cpp
  src/OpenLoco/Windows/ToolbarTopCommon.cpp
  src/OpenLoco/Windows/TownList.cpp
  src/OpenLoco/Windows/Vehicle.cpp
  src/OpenLoco/Windows/VehicleList.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review, refactor

#1481 remove globals for more company things
  src/OpenLoco/CompanyManager.cpp
  src/OpenLoco/CompanyManager.h
  src/OpenLoco/GameCommands/ChangeLoan.cpp
  src/OpenLoco/Windows/ScenarioOptions.cpp
Labels: pending review, refactor

#1468 Port over OpenRCT2 ImageId class
  src/OpenLoco/Graphics/Gfx.cpp
  src/OpenLoco/Graphics/Gfx.h
  src/OpenLoco/Graphics/ImageId.h
  src/OpenLoco/Widget.cpp
  src/OpenLoco/openloco.vcxproj
Labels: refactor

#1488 Reduce locoglobals snowandseason
  src/OpenLoco/GameCommands/CreateTree.cpp
  src/OpenLoco/GameState.h
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/Scenario.h
  src/OpenLoco/Windows/TerraForm.cpp
Labels: refactor

#1486 reduce-locoglobals - scenarioTicks2
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/S5/S5.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/ScenarioManager.cpp
  src/OpenLoco/ScenarioManager.h
Labels: refactor

#1487 remove locoglobals for scenario objectives
  src/OpenLoco/EditorController.cpp
  src/OpenLoco/GameState.h
  src/OpenLoco/OpenLoco.cpp
  src/OpenLoco/Scenario.cpp
  src/OpenLoco/ScenarioObjective.cpp
  src/OpenLoco/ScenarioObjective.h
  src/OpenLoco/Windows/CompanyWindow.cpp
  src/OpenLoco/Windows/ScenarioOptions.cpp
  src/OpenLoco/Windows/TimePanel.cpp
  src/OpenLoco/openloco.vcxproj
Labels: pending review, refactor
