Repository OpenLoco/OpenLoco, pull requests merged in 2023-02, with the labels that each got.

#1822 Implement competitor object load
  src/OpenLoco/src/Objects/CompetitorObject.cpp
Labels: reverse-engineering

#1823 Apply edge scroll only when the window has input focus
  CHANGELOG.md
  src/OpenLoco/src/Input/Keyboard.cpp
  src/OpenLoco/src/Ui.cpp
  src/OpenLoco/src/Ui.h
Labels: changelog

#1787 Implement Fill Inset Rect
  src/OpenLoco/src/Drawing/DrawingContext.h
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.h
  src/OpenLoco/src/Graphics/Colour.h
  src/OpenLoco/src/Objects/CompetitorObject.cpp
  src/OpenLoco/src/Objects/InterfaceSkinObject.h
  src/OpenLoco/src/Ui/Dropdown.cpp
  src/OpenLoco/src/Viewport.cpp
  src/OpenLoco/src/Widget.cpp
  src/OpenLoco/src/Widget.h
  src/OpenLoco/src/Window.cpp
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/src/Windows/CompanyList.cpp
  src/OpenLoco/src/Windows/CompanyWindow.cpp
  src/OpenLoco/src/Windows/Construction/StationTab.cpp
  src/OpenLoco/src/Windows/Error.cpp
  src/OpenLoco/src/Windows/IndustryList.cpp
  src/OpenLoco/src/Windows/IndustryWindow.cpp
  src/OpenLoco/src/Windows/KeyboardShortcuts.cpp
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
  src/OpenLoco/src/Windows/MapToolTip.cpp
  src/OpenLoco/src/Windows/MapWindow.cpp
  src/OpenLoco/src/Windows/MessageWindow.cpp
  src/OpenLoco/src/Windows/MusicSelection.cpp
  src/OpenLoco/src/Windows/News/News.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/src/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/src/Windows/ScenarioSelect.cpp
  src/OpenLoco/src/Windows/StationList.cpp
  src/OpenLoco/src/Windows/StationWindow.cpp
  src/OpenLoco/src/Windows/TerraForm.cpp
  src/OpenLoco/src/Windows/TextInputWindow.cpp
  src/OpenLoco/src/Windows/TileInspector.cpp
  src/OpenLoco/src/Windows/TimePanel.cpp
  src/OpenLoco/src/Windows/ToolTip.cpp
  src/OpenLoco/src/Windows/ToolbarBottomEditor.cpp
  src/OpenLoco/src/Windows/TownList.cpp
  src/OpenLoco/src/Windows/TownWindow.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
  src/OpenLoco/src/Windows/VehicleList.cpp
Labels: reverse-engineering

#1812 Implement draw structs
  src/OpenLoco/src/Drawing/DrawingContext.h
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.h
  src/OpenLoco/src/Paint/Paint.cpp
  src/OpenLoco/src/Paint/Paint.h
Labels: reverse-engineering

#1824 Implement region object load
  src/OpenLoco/src/Objects/RegionObject.cpp
  src/OpenLoco/src/Objects/RegionObject.h
Labels: pending review, reverse-engineering

#1829 Implement dock object load
  src/OpenLoco/src/Objects/DockObject.cpp
  src/OpenLoco/src/Objects/DockObject.h
Labels: pending review, reverse-engineering

#1834 Implement road station object load
  src/OpenLoco/src/Objects/RoadStationObject.cpp
  src/OpenLoco/src/Objects/RoadStationObject.h
  src/OpenLoco/src/Station.cpp
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
Labels: reverse-engineering

#1833 Implement ObjectSelectionWindow::assignTabPositions (sub_473154)
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: pending review, reverse-engineering

#1842 Track Object Load
  CHANGELOG.md
  src/OpenLoco/src/Objects/Object.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/Objects/TrackObject.cpp
  src/OpenLoco/src/Objects/TrackObject.h
  src/OpenLoco/src/Windows/Construction/Common.cpp
Labels: reverse-engineering

#1846 Road object load
  CHANGELOG.md
  src/OpenLoco/src/Objects/RoadObject.cpp
  src/OpenLoco/src/Objects/RoadObject.h
Labels: reverse-engineering

#1849 Fix regression from #1840
  src/OpenLoco/src/Ui/WindowManager.cpp
Labels: pending review

#1837 Add search/filter functionality to object selection window
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/src/Input/Keyboard.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Ui/TextInput.cpp
  src/OpenLoco/src/Ui/TextInput.h
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: pending review, changelog

#1848 Vehicle Object Load
  src/OpenLoco/src/Entities/Entity.cpp
  src/OpenLoco/src/Entities/Entity.h
  src/OpenLoco/src/Entities/EntityManager.cpp
  src/OpenLoco/src/Entities/Misc.cpp
  src/OpenLoco/src/Objects/CargoObject.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/RoadObject.cpp
  src/OpenLoco/src/Objects/SteamObject.cpp
  src/OpenLoco/src/Objects/SteamObject.h
  src/OpenLoco/src/Objects/TrackObject.cpp
  src/OpenLoco/src/Objects/VehicleObject.cpp
  src/OpenLoco/src/Objects/VehicleObject.h
  src/OpenLoco/src/Paint/PaintVehicle.cpp
  src/OpenLoco/src/Vehicles/CreateVehicle.cpp
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review, reverse-engineering

#1836 Implement fillRect
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
Labels: pending improvement, reverse-engineering

#1860 Implement VehicleMananger::updateDaily
  src/OpenLoco/src/Vehicles/Vehicle.h
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
  src/OpenLoco/src/Vehicles/VehicleManager.cpp
Labels: pending review, reverse-engineering

#1851 Implement TreeObject::load
  src/OpenLoco/src/Objects/TreeObject.cpp
  src/OpenLoco/src/Objects/TreeObject.h
  src/OpenLoco/src/Paint/PaintTree.cpp
  src/OpenLoco/src/Windows/TerraForm.cpp
Labels: pending review, reverse-engineering

#1861 Implement string width
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
Labels: reverse-engineering

#1862 Implement Draw string centred raw
  src/OpenLoco/src/Drawing/DrawingContext.h
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.h
  src/OpenLoco/src/Windows/Error.cpp
Labels: pending review, reverse-engineering
