Repository OpenLoco/OpenLoco, pull requests merged in 2023-09, with the labels that each got.

#2105 Use game state structure for trafficHandedness global
  src/OpenLoco/src/GameState.h
  src/OpenLoco/src/LastGameOptionManager.cpp
  src/OpenLoco/src/LastGameOptionManager.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
Labels: squash merge

#2018 Implement scroll view thumb update
  CHANGELOG.md
  src/OpenLoco/src/Ui/ScrollView.cpp
Labels: changelog

#2104 Load Company Face From CompanyName
  src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.cpp
  src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.h
  src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/Windows/CompanyFaceSelection.cpp
  src/OpenLoco/src/World/CompanyManager.cpp
  src/OpenLoco/src/World/CompanyManager.h
Labels: pending review

#2112 Rework routing functions to not recurse
  src/OpenLoco/src/Vehicles/Routing.cpp
Labels: pending review

#2115 Misc static analysis fixes and typos
  src/Core/include/OpenLoco/Core/EnumFlags.hpp
  src/OpenLoco/src/Drawing/DrawSprite.cpp
  src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.cpp
  src/OpenLoco/src/GameCommands/Town/RemoveTown.cpp
  src/OpenLoco/src/Graphics/Gfx.h
  src/OpenLoco/src/Map/BuildingElement.cpp
  src/OpenLoco/src/Objects/BuildingObject.cpp
  src/OpenLoco/src/Objects/BuildingObject.h
  src/OpenLoco/src/Objects/IndustryObject.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/SoundObject.h
  src/OpenLoco/src/Objects/TrainSignalObject.cpp
  src/OpenLoco/src/Objects/VehicleObject.h
  src/OpenLoco/src/Ui/Screenshot.cpp
  src/OpenLoco/src/Vehicles/OrderManager.cpp
  src/OpenLoco/src/Vehicles/Vehicle2.cpp
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/KeyboardShortcuts.cpp
  src/OpenLoco/src/Windows/News/News.cpp
  src/OpenLoco/src/Windows/ScenarioOptions.cpp
  src/OpenLoco/src/World/Company.cpp
  src/OpenLoco/src/World/TownManager.cpp
Labels: pending review, refactor

#2100 Draw String Ticker
  src/OpenLoco/src/Drawing/DrawingContext.h
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.h
  src/OpenLoco/src/Windows/News/Ticker.cpp
Labels: pending review

#2099 Implement determineAvailableVehicles
  src/OpenLoco/src/Vehicles/VehicleManager.cpp
  src/OpenLoco/src/World/Company.cpp
  src/OpenLoco/src/World/Company.h
Labels: pending review

#2116 Add 'expert mode' to object selection window
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: changelog

#2125 Change INT32_1DP to INT32_2DP
  data/language/en-GB.yml
  data/language/ko-KR.yml
  data/language/nl-NL.yml
  data/language/pl-PL.yml
  data/language/pt-BR.yml
  data/language/sk-SK.yml
  data/language/zh-CN.yml
  src/OpenLoco/src/Localisation/LanguageFiles.cpp
Labels: squash merge

#2117 Allow 0-town landscape generation as per vanilla behaviour
  CHANGELOG.md
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
Labels: enhancement, pending review, changelog
