Repository OpenLoco/OpenLoco, pull requests merged in 2023-11, with the labels that each got.

#2172 Add cstdint include to OpenAL.h
  src/OpenLoco/src/Audio/OpenAL.h
Labels: pending review

#2165 Vehicle functions: Bogie::isOnRackRail and Vehicle::removeAllCargo
  src/OpenLoco/src/GameCommands/Vehicles/VehiclePickupAir.cpp
  src/OpenLoco/src/GameCommands/Vehicles/VehiclePickupWater.cpp
  src/OpenLoco/src/Vehicles/Vehicle.cpp
  src/OpenLoco/src/Vehicles/Vehicle.h
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
  src/OpenLoco/src/Vehicles/VehicleBogie.cpp
Labels: pending review

#2177 Vehicle Functions: Implement delete car
  src/OpenLoco/src/Vehicles/VehicleManager.cpp
Labels: pending review

#2179 name train signal object's second string
  src/OpenLoco/src/Objects/ObjectStringTable.cpp
  src/OpenLoco/src/Objects/TrainSignalObject.cpp
  src/OpenLoco/src/Objects/TrainSignalObject.h
  src/OpenLoco/src/Windows/Construction/SignalTab.cpp
Labels: game object

#2178 Update CI to include Ubuntu Mantic and Fedora 39
  .github/workflows/ci.yml
  cmake/OpenLocoUtility.cmake
  src/OpenLoco/src/Windows/Options.cpp
  src/Utility/include/OpenLoco/Utility/String.hpp
  thirdparty/CMakeLists.txt
Labels: pending review

#2184 Fix slow startup on double-density displays
  CHANGELOG.md
  src/OpenLoco/src/OpenLoco.cpp
Labels: changelog

#2185 Object Selection: Part 3
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Objects/ObjectIndex.cpp
  src/OpenLoco/src/Objects/ObjectIndex.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/S5/S5.cpp
  src/OpenLoco/src/Scenario.cpp
  src/OpenLoco/src/Scenario.h
  src/OpenLoco/src/Title.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/src/Windows/Options.cpp
Labels: pending review
