Repository OpenLoco/OpenLoco, pull requests merged in 2023-08, with the labels that each got.

#1986 Create Industry GameCommand
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/ClearLand.cpp
  src/OpenLoco/src/GameCommands/CreateIndustry.cpp
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/LowerLand.cpp
  src/OpenLoco/src/GameCommands/RemoveIndustry.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/IndustryElement.cpp
  src/OpenLoco/src/Map/IndustryElement.h
  src/OpenLoco/src/Map/StationElement.h
  src/OpenLoco/src/Map/TileManager.cpp
  src/OpenLoco/src/Map/TileManager.h
  src/OpenLoco/src/Objects/IndustryObject.cpp
  src/OpenLoco/src/Objects/IndustryObject.h
  src/OpenLoco/src/World/Industry.cpp
  src/OpenLoco/src/World/Industry.h
  src/OpenLoco/src/World/IndustryManager.cpp
  src/OpenLoco/src/World/IndustryManager.h
Labels: pending review

#2062 Add definitions to two common items
  src/OpenLoco/src/Input/MouseInput.cpp
  src/OpenLoco/src/Map/BuildingElement.cpp
  src/OpenLoco/src/Map/Tile.h
  src/OpenLoco/src/Map/TileClearance.cpp
  src/OpenLoco/src/Ui/ViewportInteraction.cpp
  src/OpenLoco/src/Vehicles/Routing.cpp
  src/OpenLoco/src/Vehicles/VehicleTail.cpp
  src/OpenLoco/src/Windows/Construction/Common.cpp
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/src/Windows/Construction/SignalTab.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
  src/OpenLoco/src/World/Station.cpp
Labels: pending review

#2054 Implement OriginalTerrainGenerator::generate
  src/OpenLoco/src/Map/MapGenerator.cpp
  src/OpenLoco/src/Objects/HillShapesObject.h
Labels: pending review

#2078 Construction related bugfixes and improvements
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/Company/BuildCompanyHeadquarters.cpp
  src/OpenLoco/src/Input/Shortcuts.cpp
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Windows/CompanyWindow.cpp
  src/OpenLoco/src/Windows/Construction/Common.cpp
  src/OpenLoco/src/Windows/IndustryList.cpp
  src/OpenLoco/src/Windows/TownList.cpp
Labels: pending review, changelog

#2077 Fix crash in scenario index creation when objects removed
  CHANGELOG.md
  src/OpenLoco/src/Scenario.cpp
  src/OpenLoco/src/ScenarioManager.cpp
Labels: changelog

#2060 Add some crude protection against crashing on bad vehicles
  CHANGELOG.md
  src/OpenLoco/src/Graphics/ImageId.h
  src/OpenLoco/src/Objects/VehicleObject.cpp
Labels: changelog

#2086 Refactor MapGenerator.cpp into multiple files
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Terraform/ChangeLandMaterial.cpp
  src/OpenLoco/src/Map/MapGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator.h
  src/OpenLoco/src/Map/MapGenerator/HeightMap.h
  src/OpenLoco/src/Map/MapGenerator/HeightMapRange.h
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.h
  src/OpenLoco/src/Map/MapGenerator/ModernTerrainGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/ModernTerrainGenerator.h
  src/OpenLoco/src/Map/MapGenerator/OriginalTerrainGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/OriginalTerrainGenerator.h
  src/OpenLoco/src/Scenario.cpp
Labels: refactor

#2036 Group vehicles by type in object selection window
  CHANGELOG.md
  src/OpenLoco/src/Objects/ObjectIndex.cpp
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: feature, pending review, changelog

#2073 Implement MapWindow::assignRouteColours
  src/OpenLoco/src/Graphics/Colour.h
  src/OpenLoco/src/Windows/MapWindow.cpp
Labels: pending review

#2094 MapWindow::assignRouteColours: match vanilla for sub_478265
  src/OpenLoco/src/Windows/MapWindow.cpp
Labels: pending review

#2093 Add dev log for v23.08
  DEVELOPMENTLOG.md
Labels: pending review

#2097 Fix #2095. Incorrect waypoints set
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/Vehicles/VehicleOrderInsert.h
  src/OpenLoco/src/S5/S5.cpp
  src/OpenLoco/src/Vehicles/OrderManager.cpp
  src/OpenLoco/src/Vehicles/OrderManager.h
Labels: pending improvement, changelog
