Repository OpenLoco/OpenLoco, pull requests merged in 2023-06, with the labels that each got.

#1967 Correct data type for clear land offsets
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/ClearLand.cpp
Labels: enhancement, changelog

#1974 Move OrderManager out of VehicleManager
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Vehicles/CreateVehicle.cpp
  src/OpenLoco/src/Vehicles/OrderManager.cpp
  src/OpenLoco/src/Vehicles/OrderManager.h
  src/OpenLoco/src/Vehicles/VehicleManager.cpp
  src/OpenLoco/src/Vehicles/VehicleManager.h
  src/OpenLoco/src/Viewport.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review

#1958 Implement vehicle speed control game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/VehicleSpeedControl.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review

#1963 Make news sound effects optional
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/src/Config.cpp
  src/OpenLoco/src/Config.h
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Windows/MessageWindow.cpp
  src/OpenLoco/src/Windows/News/Common.cpp
Labels: pending review

#1954 Implement vehicle refit game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/VehicleRefit.cpp
  src/OpenLoco/src/Vehicles/Vehicle.h
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review

#1978 Move OrderRingView into OrderManager
  src/OpenLoco/src/GameCommands/CloneVehicle.cpp
  src/OpenLoco/src/GameCommands/VehicleOrderSkip.cpp
  src/OpenLoco/src/S5/S5.cpp
  src/OpenLoco/src/Vehicles/OrderManager.cpp
  src/OpenLoco/src/Vehicles/OrderManager.h
  src/OpenLoco/src/Vehicles/Orders.cpp
  src/OpenLoco/src/Vehicles/Orders.h
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
  src/OpenLoco/src/Windows/MapWindow.cpp
  src/OpenLoco/src/Windows/VehicleList.cpp
Labels: pending review

#1973 Implement vehicle order table reversing
  data/language/en-GB.yml
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/VehicleOrderReverse.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Vehicles/OrderManager.cpp
  src/OpenLoco/src/Vehicles/OrderManager.h
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review, changelog

#1980 Fix #1968. Crash when performing tile clear check
  CHANGELOG.md
  src/OpenLoco/src/Map/TileManager.cpp
Labels: changelog

#1977 Implement VehicleOrderDelete game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/VehicleOrderDelete.cpp
  src/OpenLoco/src/Vehicles/OrderManager.cpp
  src/OpenLoco/src/Vehicles/OrderManager.h
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review

#1998 Implement raiseLand and lowerLand game commands
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/ClearLand.cpp
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/LowerLand.cpp
  src/OpenLoco/src/GameCommands/RaiseLand.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/SurfaceData.cpp
  src/OpenLoco/src/Map/SurfaceData.h
  src/OpenLoco/src/Map/SurfaceElement.h
  src/OpenLoco/src/Map/Tile.h
  src/OpenLoco/src/Map/TileClearance.cpp
  src/OpenLoco/src/Map/TileClearance.h
  src/OpenLoco/src/Map/TileManager.cpp
  src/OpenLoco/src/Map/TileManager.h
Labels: pending review

#2013 Add BH/CH/D/G headers to tile inspector
  data/language/en-GB.yml
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Windows/TileInspector.cpp
Labels: changelog
