Repository OpenLoco/OpenLoco, pull requests merged in 2023-01, with the labels that each got.

#1747 Rename rock objects to cliff edge objects
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Objects/CliffEdgeObject.cpp
  src/OpenLoco/src/Objects/CliffEdgeObject.h
  src/OpenLoco/src/Objects/Object.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: pending review

#1746 Object load functions: Airport and Bridge
  src/OpenLoco/src/Objects/AirportObject.cpp
  src/OpenLoco/src/Objects/AirportObject.h
  src/OpenLoco/src/Objects/BridgeObject.cpp
Labels: reverse-engineering

#1749 Implement SnowObject::load, ScenarioTextObject::load
  src/OpenLoco/src/Objects/ScenarioTextObject.cpp
  src/OpenLoco/src/Objects/SnowObject.cpp
  src/OpenLoco/src/Objects/SnowObject.h
Labels: pending review

#1745 Implement 'Complete scenario challenge' cheat
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/src/Company.cpp
  src/OpenLoco/src/Company.h
  src/OpenLoco/src/GameCommands/Cheat.cpp
  src/OpenLoco/src/GameCommands/Cheat.h
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Windows/Cheats.cpp
Labels: pending review

#1751 Fix #1750: Scenario index is not updated when in-game language changes
  CHANGELOG.md
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/ScenarioManager.cpp
  src/OpenLoco/src/ScenarioManager.h
  src/OpenLoco/src/Windows/Options.cpp
Labels: pending review

#1752 Implement Building Object Load
  src/OpenLoco/src/Objects/BuildingObject.cpp
  src/OpenLoco/src/Objects/BuildingObject.h
  src/OpenLoco/src/Objects/Object.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
Labels: reverse-engineering

#1753 Implement several object loading functions
  src/OpenLoco/src/Objects/CargoObject.cpp
  src/OpenLoco/src/Objects/CliffEdgeObject.cpp
  src/OpenLoco/src/Objects/ClimateObject.cpp
  src/OpenLoco/src/Objects/CurrencyObject.cpp
  src/OpenLoco/src/Objects/HillShapesObject.cpp
  src/OpenLoco/src/Objects/LevelCrossingObject.cpp
  src/OpenLoco/src/Objects/RoadExtraObject.cpp
  src/OpenLoco/src/Objects/ScaffoldingObject.cpp
  src/OpenLoco/src/Objects/StreetLightObject.cpp
  src/OpenLoco/src/Objects/TownNamesObject.cpp
  src/OpenLoco/src/Objects/TrackExtraObject.cpp
  src/OpenLoco/src/Objects/TunnelObject.cpp
  src/OpenLoco/src/Objects/WallObject.cpp
  src/OpenLoco/src/Objects/WaterObject.cpp
Labels: reverse-engineering

#1754 Implement Steam Object Load
  src/OpenLoco/src/Graphics/Gfx.cpp
  src/OpenLoco/src/Graphics/Gfx.h
  src/OpenLoco/src/Objects/SteamObject.cpp
  src/OpenLoco/src/Objects/SteamObject.h
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
Labels: reverse-engineering

#1758 Implement Sound Object Load
  src/OpenLoco/src/Audio/Audio.cpp
  src/OpenLoco/src/Audio/Audio.h
  src/OpenLoco/src/Objects/LandObject.cpp
  src/OpenLoco/src/Objects/SoundObject.cpp
  src/OpenLoco/src/Objects/SoundObject.h
Labels: reverse-engineering

#1748 Keep zoomed image relations when fixing Steam G1
  CHANGELOG.md
  src/OpenLoco/src/Graphics/Gfx.cpp
Labels: changelog

#1759 Implement Train Signal and Train Station object load functions
  src/OpenLoco/src/Objects/TrainSignalObject.cpp
  src/OpenLoco/src/Objects/TrainStationObject.cpp
  src/OpenLoco/src/Objects/TrainStationObject.h
Labels: reverse-engineering

#1764 Close #1698: improve Locomotion folder prompts
  CHANGELOG.md
  src/OpenLoco/src/Environment.cpp
Labels: pending review

#1767 Implement lineDraw
  src/OpenLoco/src/Drawing/DrawingContext.h
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.cpp
  src/OpenLoco/src/Drawing/SoftwareDrawingContext.h
  src/OpenLoco/src/Windows/IndustryWindow.cpp
  src/OpenLoco/src/Windows/MapWindow.cpp
  src/OpenLoco/src/Windows/TownWindow.cpp
Labels: reverse-engineering
