Repository OpenLoco/OpenLoco, pull requests merged in 2023-05, with the labels that each got.

#1932 Fix small cpp20 issues
  src/OpenLoco/src/Audio/OpenAL.cpp
  src/OpenLoco/src/Objects/Object.h
  src/OpenLoco/src/Objects/ObjectStringTable.cpp
  src/OpenLoco/src/Objects/ScaffoldingObject.h
  src/OpenLoco/src/Vehicles/CreateVehicle.cpp
Labels: pending review

#1914 Refactor rename station args
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/RenameStation.cpp
  src/OpenLoco/src/Windows/StationWindow.cpp
Labels: pending improvement

#1926 Use more enum flags
  src/OpenLoco/src/Audio/Audio.cpp
  src/OpenLoco/src/Audio/VehicleChannel.cpp
  src/OpenLoco/src/Drawing/DrawSprite.cpp
  src/OpenLoco/src/Drawing/DrawSprite.h
  src/OpenLoco/src/Drawing/DrawSpriteBMP.hpp
  src/OpenLoco/src/Drawing/DrawSpriteHelper.hpp
  src/OpenLoco/src/Drawing/DrawSpriteRLE.hpp
  src/OpenLoco/src/Paint/Paint.h
  src/OpenLoco/src/ScenarioManager.cpp
  src/OpenLoco/src/ScenarioManager.h
  src/OpenLoco/src/Vehicles/CreateVehicle.cpp
  src/OpenLoco/src/Vehicles/Vehicle.h
  src/OpenLoco/src/Windows/Construction/Common.cpp
  src/OpenLoco/src/Windows/Construction/Construction.h
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/src/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/src/Windows/Construction/SignalTab.cpp
  src/OpenLoco/src/Windows/Construction/StationTab.cpp
Labels: pending review

#1943 Add cstdint include in two more headers for gcc 13.1
  src/OpenLoco/src/CommandLine.h
  src/OpenLoco/src/Localisation/Languages.h
Labels: pending review

#1940 Refactor tool related loco_globals into ToolManager
  CHANGELOG.md
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Input.h
  src/OpenLoco/src/Input/MouseInput.cpp
  src/OpenLoco/src/Ui.cpp
  src/OpenLoco/src/Ui.h
  src/OpenLoco/src/Ui/ToolManager.cpp
  src/OpenLoco/src/Ui/ToolManager.h
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Window.cpp
  src/OpenLoco/src/Windows/CompanyList.cpp
  src/OpenLoco/src/Windows/Construction/Common.cpp
  src/OpenLoco/src/Windows/Construction/Construction.h
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/src/Windows/Construction/OverheadTab.cpp
  src/OpenLoco/src/Windows/MessageWindow.cpp
  src/OpenLoco/src/Windows/TerraForm.cpp
  src/OpenLoco/src/Windows/TownList.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review, changelog

#1918 refactoring the args for change company name command
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/RenameCompanyName.cpp
  src/OpenLoco/src/Windows/CompanyWindow.cpp
  src/OpenLoco/src/World/CompanyManager.cpp
Labels: pending review

#1919 refactoring the args of change company owner name command
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/RenameCompanyOwner.cpp
  src/OpenLoco/src/Windows/CompanyWindow.cpp
  src/OpenLoco/src/World/CompanyManager.cpp
Labels: pending review

#1956 Update introduction for README.md
  README.md
Labels: pending review

#1955 Fix #1953: Cloning a vehicle doesn't copy cargo retrofit selection
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/Vehicles/CloneVehicle.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review

#1965 Implement SDL hardware rendering
  CHANGELOG.md
  src/OpenLoco/src/Drawing/SoftwareDrawingEngine.cpp
  src/OpenLoco/src/Drawing/SoftwareDrawingEngine.h
  src/OpenLoco/src/Ui.h
Labels: changelog
