Repository OpenLoco/OpenLoco, pull requests merged in 2023-03, with the labels that each got.

#1872 Implement basis for clear land game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/ClearLand.cpp
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/Windows/TerraForm.cpp
Labels: reverse-engineering

#1877 Fix mistake in vehicle object load.
  src/OpenLoco/src/Objects/VehicleObject.cpp
Labels: pending review

#1883 Fix hang when crashing uncleanly
  CHANGELOG.md
  src/OpenLoco/src/Audio/OpenAL.cpp
  src/OpenLoco/src/OpenLoco.cpp
Labels: pending review, changelog

#1884 Add legacy default config
  src/OpenLoco/src/Config.cpp
Labels: pending review

#1740 Town Grow Functions
  src/Core/include/OpenLoco/Core/Prng.h
  src/OpenLoco/src/World/Town.cpp
  src/OpenLoco/src/World/Town.h
  src/OpenLoco/src/World/TownManager.cpp
Labels: reverse-engineering

#1742 Town Grow 2
  src/OpenLoco/src/Objects/RoadObject.h
  src/OpenLoco/src/World/Town.cpp
  src/OpenLoco/src/World/Town.h
  src/OpenLoco/src/World/TownManager.cpp
Labels: reverse-engineering
