Repository OpenLoco/OpenLoco, pull requests merged in 2024-05, with the labels that each got.

#2471 Changelog: consistently order 'Change' lines before 'Fix' lines
  CHANGELOG.md
Labels: pending review

#2466 Unload scenarioText objects when entering custom title
  CHANGELOG.md
  src/OpenLoco/src/Windows/ScenarioOptions.cpp
Labels: pending review, changelog

#2476 Fix passing the incorrect buffer size for buffer strings
  CHANGELOG.md
  src/OpenLoco/src/Objects/ObjectIndex.cpp
  src/OpenLoco/src/S5/S5.cpp
Labels: changelog

#2475 Allow removing protected structures when sandbox mode is enabled
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/Buildings/RemoveBuilding.cpp
  src/OpenLoco/src/Objects/BuildingObject.h
  src/OpenLoco/src/Ui/ViewportInteraction.cpp
Labels: pending review

#2483 Replace direct refs to 0x00525F62 with _gameState->var_014A
  src/OpenLoco/src/S5/S5.cpp
Labels: pending review

#2443 Implement MapWindow::setMapPixels
  src/OpenLoco/src/Graphics/Colour.h
  src/OpenLoco/src/Windows/MapWindow.cpp
Labels: pending review, squash merge

#2459 Paint surface
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Graphics/Colour.cpp
  src/OpenLoco/src/Graphics/Colour.h
  src/OpenLoco/src/Graphics/ImageId.h
  src/OpenLoco/src/Graphics/ImageIds.h
  src/OpenLoco/src/Map/MapSelection.cpp
  src/OpenLoco/src/Map/MapSelection.h
  src/OpenLoco/src/Map/WaveManager.cpp
  src/OpenLoco/src/Map/WaveManager.h
  src/OpenLoco/src/Objects/IndustryObject.h
  src/OpenLoco/src/Objects/LandObject.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/WaterObject.cpp
  src/OpenLoco/src/Paint/Paint.cpp
  src/OpenLoco/src/Paint/Paint.h
  src/OpenLoco/src/Paint/PaintBuilding.cpp
  src/OpenLoco/src/Paint/PaintIndustry.cpp
  src/OpenLoco/src/Paint/PaintSurface.cpp
  src/OpenLoco/src/Paint/PaintSurface.h
  src/OpenLoco/src/Paint/PaintTile.cpp
  src/OpenLoco/src/World/Station.cpp
  src/OpenLoco/src/World/Station.h
Labels: pending review

#2486 Hide progress bars for autosaves
  CHANGELOG.md
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/S5/S5.cpp
  src/OpenLoco/src/S5/S5.h
Labels: pending review

#2487 Implement drawString Y offsets
  src/OpenLoco/src/Graphics/DrawingContext.h
  src/OpenLoco/src/Graphics/SoftwareDrawingContext.cpp
  src/OpenLoco/src/Graphics/SoftwareDrawingContext.h
Labels: pending review
