Repository OpenLoco/OpenLoco, pull requests merged in 2024-11, with the labels that each got.

#2691 Fix modulo operation on negatives in terrain gen
  CHANGELOG.md
  src/OpenLoco/src/Map/MapGenerator/OriginalTerrainGenerator.cpp
Labels: changelog

#2697 Add OpenGraphics objects
  CHANGELOG.md
  CMakeLists.txt
  data/language/en-GB.yml
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Objects/Object.h
  src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp
Labels: changelog

#2688 Improve the tile game save compare
  src/OpenLoco/src/GameSaveCompare.cpp
Labels: pending review

#2696 Fix #2690. Unable to remove certain multi tile track
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/Track/RemoveTrack.cpp
  src/OpenLoco/src/Ui/Windows/Construction/ConstructionTab.cpp
Labels: pending review

#2683 Fix #2678. Train bogie body draw order and body bound box
  CHANGELOG.md
  src/OpenLoco/src/Paint/PaintVehicle.cpp
  src/OpenLoco/src/Ui/Windows/DragVehiclePart.cpp
  src/OpenLoco/src/Ui/Windows/Vehicle.cpp
  src/OpenLoco/src/Vehicles/VehicleDraw.cpp
  src/OpenLoco/src/Vehicles/VehicleDraw.h
Labels: pending review

#2707 Enable correct reporting for __cplusplus
  cmake/OpenLocoUtility.cmake
Labels: pending review

#2717 Fix crash when river meander rate is 1 unit
  CHANGELOG.md
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
Labels: bug-openloco, changelog

#2719 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: documentation

#2708 Make "Show Options Window" keyboard shortcut work in title screen
  CHANGELOG.md
  src/OpenLoco/src/Input/Keyboard.cpp
Labels: enhancement-minor, changelog

#2735 Fix map generator not updating tree seasons
  CHANGELOG.md
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Objects/ObjectIndex.cpp
  src/OpenLoco/src/Ui/Windows/Construction/StationTab.cpp
  src/OpenLoco/src/Vehicles/OrderManager.cpp
Labels: changelog

#2737 Implement paint road station
  src/OpenLoco/src/Objects/RoadStationObject.cpp
  src/OpenLoco/src/Objects/RoadStationObject.h
  src/OpenLoco/src/Paint/PaintRoadStation.cpp
Labels: pending review

#2699 Simplify & modularise music playlist code
  CONTRIBUTORS.md
  src/OpenLoco/src/Audio/Audio.cpp
  src/OpenLoco/src/Audio/Audio.h
  src/OpenLoco/src/Ui/Windows/Options.cpp
Labels: refactor

#2749 move ZehMatt and LeftofZen to Development Team
  CONTRIBUTORS.md
Labels: documentation

#2744 Implement paint supports
  src/OpenLoco/src/Paint/PaintTile.cpp
Labels: reverse-engineering

#2724 Prevent object loading crashing on malformed imagetables
  CHANGELOG.md
  src/OpenLoco/src/Objects/ObjectImageTable.cpp
  src/OpenLoco/src/Objects/ObjectManager.cpp
Labels: changelog

#2736 Company Ai: Purchase Vehicle
  src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp
  src/OpenLoco/src/Vehicles/Vehicle.h
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
  src/OpenLoco/src/World/Company.cpp
  src/OpenLoco/src/World/Company.h
  src/OpenLoco/src/World/CompanyAi.cpp
  src/OpenLoco/src/World/CompanyAi.h
Labels: reverse-engineering

#2770 Show object filenames without directories
  CHANGELOG.md
  src/OpenLoco/src/Ui/Windows/ObjectSelectionWindow.cpp
Labels: pending review, changelog

#2743 Update sound pausing on title screen to match original behaviour
  CHANGELOG.md
  src/OpenLoco/src/Audio/Audio.cpp
  src/OpenLoco/src/Game.cpp
  src/OpenLoco/src/Ui/Windows/PromptSaveWindow.cpp
Labels: enhancement-epic, changelog
