Repository OpenLoco/OpenLoco, pull requests merged in 2024-03, with the labels that each got.

#2168 Create a save game compare command line tool #1013
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/CommandLine.cpp
  src/OpenLoco/src/CommandLine.h
  src/OpenLoco/src/GameSaveCompare.cpp
  src/OpenLoco/src/GameSaveCompare.h
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/S5/S5.cpp
  src/OpenLoco/src/S5/S5.h
Labels: pending review

#2314 Landscape generation refactor
  data/language/en-GB.yml
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/SimplexTerrainGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/SimplexTerrainGenerator.h
  src/OpenLoco/src/S5/S5.h
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
Labels: refactor

#2322 Re-add missing resize event to news window
  CHANGELOG.md
  src/OpenLoco/src/Windows/News/News.cpp
Labels: changelog

#2333 Integrate TextInputWindow::_callingWindowType
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Windows/TextInputWindow.cpp
Labels: pending review

#2325 Implement MapGenerator::generateSurfaceVariation
  src/OpenLoco/src/Audio/Audio.cpp
  src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/SurfaceElement.h
  src/OpenLoco/src/Map/TileManager.cpp
  src/OpenLoco/src/Objects/ObjectIndex.cpp
  src/OpenLoco/src/World/Industry.cpp
Labels: pending review

#2317 Implement Create Road Station
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
  src/OpenLoco/src/GameCommands/Road/CreateRoadStation.h
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/RoadElement.h
  src/OpenLoco/src/Map/Track/TrackData.cpp
  src/OpenLoco/src/Map/Track/TrackData.h
  src/OpenLoco/src/Objects/RoadObject.h
  src/OpenLoco/src/Objects/RoadStationObject.h
  src/OpenLoco/src/World/Station.cpp
  src/OpenLoco/src/World/Station.h
Labels: pending review

#2328 Give water options their own tab in the landscape generation window
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
Labels: changelog

#2355 Replace direct users of 0x00525E28 with Game::hasFlags
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/Objects/ObjectIndex.cpp
Labels: pending review

#2323 Implement MapGenerator::generateLand
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
Labels: pending review

#2308 Implement update level crossing
  src/OpenLoco/src/GameSaveCompare.cpp
  src/OpenLoco/src/GameState.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/ObjectManager.h
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/S5/S5.h
Labels: pending review

#2353 Rework generator options in landscape generation window
  data/language/en-GB.yml
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/MapGenerator/SimplexTerrainGenerator.cpp
  src/OpenLoco/src/S5/S5.h
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: pending review, changelog

#1941 add png heightmap loading for terrain generation
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Environment.cpp
  src/OpenLoco/src/Environment.h
  src/OpenLoco/src/Game.cpp
  src/OpenLoco/src/Game.h
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.h
  src/OpenLoco/src/Map/MapGenerator/PngImage.cpp
  src/OpenLoco/src/Map/MapGenerator/PngImage.h
  src/OpenLoco/src/Map/MapGenerator/PngTerrainGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/PngTerrainGenerator.h
  src/OpenLoco/src/S5/S5.h
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
Labels: feature, changelog

#2364 Always use mouse down event for stepper widgets
  CHANGELOG.md
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
  src/OpenLoco/src/Windows/TileInspector.cpp
Labels: pending review

#2347 Fix train station again
  src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
Labels: pending review

#2338 Implement MapGenerator::generateIndustries
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/World/IndustryManager.cpp
  src/OpenLoco/src/World/IndustryManager.h
Labels: pending review

#2381 Fix text cursor not rendering at correct position
  CHANGELOG.md
  src/OpenLoco/src/Windows/TextInputWindow.cpp
Labels: pending review
