Repository OpenLoco/OpenLoco, pull requests merged in 2024-08, with the labels that each got.

#2570 Fix #2520: Crash when loading from title screen
  CHANGELOG.md
  src/OpenLoco/src/Audio/VehicleChannel.cpp
  src/OpenLoco/src/S5/S5.cpp
Labels: changelog

#2572 Paint docks and airports
  src/OpenLoco/src/GameCommands/Vehicles/VehiclePlaceAir.cpp
  src/OpenLoco/src/Objects/AirportObject.cpp
  src/OpenLoco/src/Objects/AirportObject.h
  src/OpenLoco/src/Objects/DockObject.cpp
  src/OpenLoco/src/Objects/DockObject.h
  src/OpenLoco/src/Paint/PaintAirport.cpp
  src/OpenLoco/src/Paint/PaintBuilding.cpp
  src/OpenLoco/src/Paint/PaintDocks.cpp
  src/OpenLoco/src/Paint/PaintIndustry.cpp
  src/OpenLoco/src/Vehicles/Vehicle.cpp
  src/OpenLoco/src/Vehicles/Vehicle.h
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
Labels: pending review

#2577 Save playNewsSounds option on change
  CHANGELOG.md
  src/OpenLoco/src/Windows/MessageWindow.cpp
Labels: changelog

#2579 Rework error window to improve text contrast
  CHANGELOG.md
  src/OpenLoco/src/Windows/Error.cpp
Labels: changelog

#2537 Implement ensureCompanyFunding
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/World/Company.cpp
  src/OpenLoco/src/World/CompanyManager.cpp
  src/OpenLoco/src/World/CompanyManager.h
Labels: pending review

#2578 Hide scrollbars when there is nothing to scroll
  CHANGELOG.md
  src/OpenLoco/src/Input/MouseInput.cpp
  src/OpenLoco/src/Ui/ScrollView.cpp
  src/OpenLoco/src/Ui/Widget.cpp
Labels: changelog

#2586 Cleanup build vehicle window
  src/OpenLoco/src/Windows/BuildVehicle.cpp
Labels: pending review

#2590 Implement two reset surface functions
  src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp
  src/OpenLoco/src/Map/SurfaceElement.cpp
  src/OpenLoco/src/Map/TileManager.cpp
  src/OpenLoco/src/Map/TileManager.h
Labels: pending review

#2174 Update track motion
  src/OpenLoco/src/Vehicles/RoutingManager.cpp
  src/OpenLoco/src/Vehicles/RoutingManager.h
  src/OpenLoco/src/Vehicles/Vehicle.cpp
  src/OpenLoco/src/Vehicles/Vehicle.h
Labels: pending review

#2580 Paint Road
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Graphics/ImageIds.h
  src/OpenLoco/src/Map/RoadElement.h
  src/OpenLoco/src/Objects/RoadObject.h
  src/OpenLoco/src/Objects/StreetLightObject.h
  src/OpenLoco/src/Paint/Paint.cpp
  src/OpenLoco/src/Paint/Paint.h
  src/OpenLoco/src/Paint/PaintRoad.cpp
  src/OpenLoco/src/Paint/PaintRoad.h
  src/OpenLoco/src/Paint/PaintRoadCommonData.h
  src/OpenLoco/src/Paint/PaintRoadStyle0Data.h
  src/OpenLoco/src/Paint/PaintRoadStyle1Data.h
  src/OpenLoco/src/Paint/PaintRoadStyle2Data.h
  src/OpenLoco/src/Paint/PaintTile.cpp
  src/OpenLoco/src/Paint/PaintTileDecorations.cpp
  src/OpenLoco/src/Paint/PaintTileDecorations.h
  src/OpenLoco/src/Paint/PaintTrackAdditionsData.h
  src/OpenLoco/src/Paint/PaintTrackData.h
Labels: pending review

#2594 Implement MapGenerator::generateTerrainInRandomAreas
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
Labels: pending review

#2603 Fix #2372. Large square stations could not be created
  CHANGELOG.md
  src/OpenLoco/src/World/StationManager.cpp
Labels: changelog

#2585 Implement Create Airport
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Airports/CreateAirport.cpp
  src/OpenLoco/src/GameCommands/Airports/CreateAirport.h
  src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Objects/AirportObject.h
  src/OpenLoco/src/World/Station.h
Labels: pending review

#2600 Allow regenerating landscape from all lanscape setting tabs
  CHANGELOG.md
  src/OpenLoco/src/Windows/LandscapeGeneration.cpp
Labels: pending review, changelog

#2601 Fix selective minimap map blinks
  CHANGELOG.md
  src/OpenLoco/src/Windows/MapWindow.cpp
Labels: changelog
