Repository OpenLoco/OpenLoco, pull requests merged in 2024-01, with the labels that each got.

#2231 Make viewport see-through flags more granular
  CHANGELOG.md
  data/language/en-GB.yml
  src/OpenLoco/src/Input/Shortcuts.cpp
  src/OpenLoco/src/Input/Shortcuts.h
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Paint/Paint.cpp
  src/OpenLoco/src/Paint/PaintTrack.cpp
  src/OpenLoco/src/Ui/ViewportInteraction.cpp
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Viewport.cpp
  src/OpenLoco/src/Viewport.hpp
  src/OpenLoco/src/Window.cpp
  src/OpenLoco/src/Windows/ToolbarTopCommon.cpp
Labels: feature

#2229 Move edge scrolling section to NewConfig struct and reorder
  src/OpenLoco/src/Config.cpp
  src/OpenLoco/src/Config.h
  src/OpenLoco/src/Input/Keyboard.cpp
  src/OpenLoco/src/Windows/Options.cpp
Labels: pending review

#2239 clip text inside dropdown widgets
  src/OpenLoco/src/Widget.cpp
Labels: enhancement

#2243 Land tool: disable surface corner selection in mountain or paint mode
  src/OpenLoco/src/Windows/TerraForm.cpp
Labels: pending review

#2232 Turn window-specific handleInput functions into keyUp events
  src/OpenLoco/src/Input/Keyboard.cpp
  src/OpenLoco/src/Ui/TextInput.cpp
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Window.cpp
  src/OpenLoco/src/Window.h
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/src/Windows/PromptOkCancelWindow.cpp
  src/OpenLoco/src/Windows/TextInputWindow.cpp
Labels: pending review

#2240 Fix #2162: Unlink Build Vehicle window when linked vehicle window is closed
  CHANGELOG.md
  src/OpenLoco/src/Windows/BuildVehicle.cpp
Labels: changelog

#2244 Fix #2238: Scroll on map edge doesn't work for bottom and right edges
  CHANGELOG.md
  src/OpenLoco/src/Input/Keyboard.cpp
Labels: pending review

#2253 Disable SafeSeh linking to fix #2252
  CHANGELOG.md
  cmake/OpenLocoUtility.cmake
Labels: changelog

#2256 Update sound id names
  src/OpenLoco/src/Audio/Audio.h
Labels: refactor

#2270 Refactor various window (manager) bits
  src/OpenLoco/src/EditorController.cpp
  src/OpenLoco/src/Game.cpp
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/Gui.cpp
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/Ui/Screenshot.cpp
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Windows/CompanyWindow.cpp
  src/OpenLoco/src/Windows/Construction/Common.cpp
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
  src/OpenLoco/src/Windows/Error.cpp
  src/OpenLoco/src/Windows/IndustryList.cpp
  src/OpenLoco/src/Windows/Main.cpp
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/src/Windows/TerraForm.cpp
  src/OpenLoco/src/Windows/TitleMenu.cpp
  src/OpenLoco/src/Windows/TownList.cpp
Labels: pending review
