Repository OpenLoco/OpenLoco, pull requests merged in 2024-06, with the labels that each got.

#2505 Implement tile defrag function
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/TileManager.cpp
  src/OpenLoco/src/Map/TileManager.h
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/S5/S5.cpp
Labels: pending review

#2509 Add optional keyboard shortcut for options window
  CHANGELOG.md
  data/language/de-DE.yml
  data/language/en-GB.yml
  data/language/ru-RU.yml
  src/OpenLoco/src/Input/Shortcuts.cpp
  src/OpenLoco/src/Input/Shortcuts.h
  src/OpenLoco/src/Localisation/StringIds.h
Labels: changelog, squash merge

#2371 Fix music stop when loading saved game in title screen
  CHANGELOG.md
  src/OpenLoco/src/Game.cpp
  src/OpenLoco/src/Windows/PromptSaveWindow.cpp
Labels: changelog

#2337 Ignore music playing state when game is paused
  CHANGELOG.md
  src/OpenLoco/src/Audio/Audio.cpp
  src/OpenLoco/src/Audio/Audio.h
Labels: changelog

#2356 Implement MapGenerator::generateMiscBuildingType1
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Objects/IndustryObject.h
Labels: pending review

#2513 Implement Draw Vehicle Overview
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Objects/RoadObject.h
  src/OpenLoco/src/Objects/VehicleObject.cpp
  src/OpenLoco/src/Paint/PaintVehicle.cpp
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Vehicles/VehicleDraw.cpp
  src/OpenLoco/src/Vehicles/VehicleDraw.h
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/News/News.cpp
Labels: pending review

#2519 Implement updateWaterPalette (0x004C57A6)
  src/OpenLoco/src/Graphics/PaletteMap.cpp
  src/OpenLoco/src/Graphics/PaletteMap.h
  src/OpenLoco/src/Objects/ObjectManager.cpp
  src/OpenLoco/src/Objects/WaterObject.h
Labels: pending review
