Repository OpenLoco/OpenLoco, pull requests merged in 2024-02, with the labels that each got.

#2275 Update checkout version for GitHub Actions
  .github/workflows/ci.yml
Labels: pending review

#2222 Implement PaintWall
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Terraform/CreateWall.cpp
  src/OpenLoco/src/Graphics/Colour.cpp
  src/OpenLoco/src/Graphics/Colour.h
  src/OpenLoco/src/Map/SurfaceData.cpp
  src/OpenLoco/src/Map/Tile.h
  src/OpenLoco/src/Map/TileElementBase.h
  src/OpenLoco/src/Map/WallElement.h
  src/OpenLoco/src/Objects/WallObject.cpp
  src/OpenLoco/src/Objects/WallObject.h
  src/OpenLoco/src/Paint/PaintTile.cpp
  src/OpenLoco/src/Paint/PaintWall.cpp
  src/OpenLoco/src/Paint/PaintWall.h
  src/OpenLoco/src/Windows/TileInspector.cpp
Labels: pending review

#2272 Update Object Headers with latest findings
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Company/ChangeCompanyFace.cpp
  src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp
  src/OpenLoco/src/GameCommands/Terraform/CreateTree.cpp
  src/OpenLoco/src/GameCommands/Vehicles/CreateVehicle.cpp
  src/OpenLoco/src/GameCommands/Vehicles/VehicleRefit.cpp
  src/OpenLoco/src/Graphics/Gfx.cpp
  src/OpenLoco/src/Map/BuildingElement.cpp
  src/OpenLoco/src/Map/IndustryElement.cpp
  src/OpenLoco/src/Map/IndustryElement.h
  src/OpenLoco/src/Map/TileManager.cpp
  src/OpenLoco/src/Objects/BuildingCommon.h
  src/OpenLoco/src/Objects/BuildingObject.cpp
  src/OpenLoco/src/Objects/BuildingObject.h
  src/OpenLoco/src/Objects/CargoObject.cpp
  src/OpenLoco/src/Objects/CargoObject.h
  src/OpenLoco/src/Objects/CompetitorObject.cpp
  src/OpenLoco/src/Objects/CompetitorObject.h
  src/OpenLoco/src/Objects/DockObject.cpp
  src/OpenLoco/src/Objects/HillShapesObject.cpp
  src/OpenLoco/src/Objects/HillShapesObject.h
  src/OpenLoco/src/Objects/IndustryObject.cpp
  src/OpenLoco/src/Objects/IndustryObject.h
  src/OpenLoco/src/Objects/InterfaceSkinObject.h
  src/OpenLoco/src/Objects/LandObject.cpp
  src/OpenLoco/src/Objects/LandObject.h
  src/OpenLoco/src/Objects/TreeObject.cpp
  src/OpenLoco/src/Objects/TreeObject.h
  src/OpenLoco/src/Objects/VehicleObject.cpp
  src/OpenLoco/src/Objects/VehicleObject.h
  src/OpenLoco/src/Paint/PaintIndustry.cpp
  src/OpenLoco/src/Ui/ViewportInteraction.cpp
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/Construction/Common.cpp
  src/OpenLoco/src/Windows/Vehicle.cpp
  src/OpenLoco/src/World/Company.cpp
  src/OpenLoco/src/World/Station.cpp
Labels: refactor

#2284 Add .gitattributes file
  .gitattributes
  src/OpenLoco/src/Ui/LastMapWindowAttributes.h
Labels: pending review

#2283 Implement company Ai end function
  CHANGELOG.md
  src/OpenLoco/src/World/Company.h
  src/OpenLoco/src/World/CompanyAi.cpp
  src/OpenLoco/src/World/CompanyAi.h
Labels: changelog

#2292 Fix #2287: Scroll wheel not working in load/save window
  CHANGELOG.md
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
Labels: pending review

#2294 Fix #2293: see-through trees flag is ignored when right-clicking
  CHANGELOG.md
  src/OpenLoco/src/Ui/ViewportInteraction.cpp
Labels: pending review

#2297 Minor changelog clarifications
  CHANGELOG.md
Labels: pending review

#2304 Constexpr event list refactor (windows M-S)
  src/OpenLoco/src/Windows/Main.cpp
  src/OpenLoco/src/Windows/MapToolTip.cpp
  src/OpenLoco/src/Windows/MapWindow.cpp
  src/OpenLoco/src/Windows/MessageWindow.cpp
  src/OpenLoco/src/Windows/MusicSelection.cpp
  src/OpenLoco/src/Windows/NetworkStatus.cpp
  src/OpenLoco/src/Windows/News/Common.cpp
  src/OpenLoco/src/Windows/News/News.cpp
  src/OpenLoco/src/Windows/News/News.h
  src/OpenLoco/src/Windows/News/Ticker.cpp
  src/OpenLoco/src/Windows/ObjectLoadError.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/src/Windows/Options.cpp
  src/OpenLoco/src/Windows/PlayerInfoPanel.cpp
  src/OpenLoco/src/Windows/ProgressBar.cpp
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/src/Windows/PromptOkCancelWindow.cpp
  src/OpenLoco/src/Windows/PromptSaveWindow.cpp
  src/OpenLoco/src/Windows/ScenarioOptions.cpp
  src/OpenLoco/src/Windows/ScenarioSelect.cpp
  src/OpenLoco/src/Windows/StationList.cpp
  src/OpenLoco/src/Windows/StationWindow.cpp
Labels: pending review

#2310 Fix issue with station clearance
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
Labels: changelog

#2312 Fix issues with object selection
  CHANGELOG.md
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
Labels: changelog
