Repository OpenLoco/OpenLoco, pull requests merged in 2024-07, with the labels that each got.

#2523 Fix bug with autosave frequency
  CHANGELOG.md
  src/OpenLoco/src/OpenLoco.cpp
Labels: changelog

#2527 Fix ghost vehicles staying placed down when placement is interrupted
  CHANGELOG.md
  src/OpenLoco/src/Windows/Vehicle.cpp
Labels: pending review, changelog

#2545 Switch to statically compiled dependencies
  CHANGELOG.md
  CMakePresets.json
  cmake/OpenLocoUtility.cmake
  src/OpenLoco/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: changelog

#2542 Remove more old code from OpenLoco.cpp
  src/OpenLoco/src/Graphics/Gfx.cpp
  src/OpenLoco/src/OpenLoco.cpp
Labels: pending review, squash merge

#2547 Track Connections Refactor
  src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
  src/OpenLoco/src/GameCommands/Track/CreateSignal.cpp
  src/OpenLoco/src/Map/Track/Track.cpp
  src/OpenLoco/src/Map/Track/Track.h
  src/OpenLoco/src/Vehicles/Routing.cpp
  src/OpenLoco/src/Vehicles/VehicleHead.cpp
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
Labels: pending review

#2541 Implement Create Port Game Command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Docks/CreatePort.cpp
  src/OpenLoco/src/GameCommands/Docks/CreatePort.h
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/GameCommands.h
  src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/TileClearance.cpp
  src/OpenLoco/src/Objects/DockObject.cpp
  src/OpenLoco/src/Objects/DockObject.h
Labels: pending review

#2553 Implement removeStationFromList
  src/OpenLoco/src/Windows/StationList.cpp
Labels: pending review

#2550 Implement sprite interaction
  src/OpenLoco/src/Paint/Paint.cpp
Labels: testing required
