Repository OpenLoco/OpenLoco, pull requests merged in 2024-04, with the labels that each got.

#2330 Generate track meta data
  src/Core/include/OpenLoco/Core/EnumFlags.hpp
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
  src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
  src/OpenLoco/src/Map/Track/Track.h
  src/OpenLoco/src/Map/Track/TrackData.cpp
  src/OpenLoco/src/Map/Track/TrackData.h
  src/OpenLoco/src/Map/Track/TrackEnum.h
  src/OpenLoco/src/Objects/BridgeObject.h
  src/OpenLoco/src/Objects/RoadExtraObject.h
  src/OpenLoco/src/Objects/RoadObject.h
  src/OpenLoco/src/Objects/RoadStationObject.h
  src/OpenLoco/src/Objects/TrackExtraObject.h
  src/OpenLoco/src/Objects/TrackObject.cpp
  src/OpenLoco/src/Objects/TrackObject.h
  src/OpenLoco/src/Objects/TrainStationObject.h
  src/OpenLoco/src/Paint/PaintSignal.cpp
  src/OpenLoco/src/Vehicles/Routing.cpp
  src/OpenLoco/src/Vehicles/Vehicle1.cpp
  src/OpenLoco/src/Vehicles/VehicleBody.cpp
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
Labels: pending review

#2329 Create Track Game Command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/Track/CreateTrack.cpp
  src/OpenLoco/src/GameCommands/Track/CreateTrack.h
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/RoadElement.h
  src/OpenLoco/src/Map/TileClearance.cpp
  src/OpenLoco/src/Map/TileClearance.h
  src/OpenLoco/src/Map/Track/TrackData.h
  src/OpenLoco/src/Map/TrackElement.h
  src/OpenLoco/src/Objects/BridgeObject.h
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
Labels: reverse-engineering

#2396 Fix crash when creating too big a station
  CHANGELOG.md
  src/OpenLoco/src/GameCommands/Road/CreateRoadStation.cpp
  src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
Labels: changelog

#2368 Implement createBuilding game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Buildings/CreateBuilding.cpp
  src/OpenLoco/src/GameCommands/Buildings/CreateBuilding.h
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/Industries/CreateIndustry.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/BuildingElement.h
  src/OpenLoco/src/Map/TileClearance.cpp
Labels: pending review

#2382 Fix heightmap mirroring
  CHANGELOG.md
  src/OpenLoco/src/Map/MapGenerator/PngTerrainGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/PngTerrainGenerator.h
Labels: changelog

#2383 Implement terrain generation
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/Map/MapGenerator/HeightMap.cpp
  src/OpenLoco/src/Map/MapGenerator/HeightMap.h
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/SurfaceElement.h
  src/OpenLoco/src/Map/TileManager.cpp
Labels: reverse-engineering

#2413 Readd config check for gridlines
  CHANGELOG.md
  src/OpenLoco/src/Windows/Main.cpp
Labels: changelog

#2416 Make focus optional for text input widgets
  CHANGELOG.md
  src/OpenLoco/src/Input.h
  src/OpenLoco/src/Input/MouseInput.cpp
  src/OpenLoco/src/Windows/BuildVehicle.cpp
  src/OpenLoco/src/Windows/ObjectSelectionWindow.cpp
  src/OpenLoco/src/Windows/PromptBrowseWindow.cpp
  src/OpenLoco/src/Windows/TextInputWindow.cpp
Labels: changelog

#2411 Promote use of internal progress bars
  CHANGELOG.md
  data/language/de-DE.yml
  data/language/en-GB.yml
  data/language/en-US.yml
  data/language/es-ES.yml
  data/language/fr-FR.yml
  data/language/it-IT.yml
  data/language/ja-JP.yml
  data/language/ko-KR.yml
  data/language/nl-NL.yml
  data/language/pl-PL.yml
  data/language/pt-BR.yml
  data/language/ru-RU.yml
  data/language/sk-SK.yml
  data/language/zh-CN.yml
  src/OpenLoco/src/Graphics/Gfx.cpp
  src/OpenLoco/src/Gui.cpp
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Map/MapGenerator/MapGenerator.cpp
  src/OpenLoco/src/Map/MapGenerator/SimplexTerrainGenerator.cpp
  src/OpenLoco/src/OpenLoco.cpp
  src/OpenLoco/src/ScenarioManager.cpp
Labels: changelog

#2423 Add progress bars to gamestate import/export
  CHANGELOG.md
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/S5/S5.cpp
Labels: pending review

#2435 Clean up visitor pattern in Title.cpp
  src/OpenLoco/src/Title.cpp
Labels: pending review

#2437 Increase window limit from 12 to 64
  CHANGELOG.md
  src/OpenLoco/src/Ui/WindowManager.cpp
Labels: pending review

#2427 Implement further Dutch localization
  data/language/nl-NL.yml
Labels: localisation

#2445 Update sfl to 1.4.0
  thirdparty/CMakeLists.txt
Labels: build

#2447 Refactor MapWindow::setHoverItemTab
  src/OpenLoco/src/Windows/MapWindow.cpp
Labels: refactor

#2410 Implement removeTrainStation game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/GameCommands/Track/CreateTrainStation.cpp
  src/OpenLoco/src/GameCommands/Track/RemoveTrainStation.cpp
  src/OpenLoco/src/GameCommands/Track/RemoveTrainStation.h
  src/OpenLoco/src/World/Station.cpp
  src/OpenLoco/src/World/Station.h
Labels: pending review

#2455 Speed up ScenarioManager::loadScenarioProgress
  CHANGELOG.md
  src/OpenLoco/src/ScenarioManager.cpp
Labels: pending review, changelog

#2439 Implement removePort game command
  src/OpenLoco/CMakeLists.txt
  src/OpenLoco/src/GameCommands/Docks/RemovePort.cpp
  src/OpenLoco/src/GameCommands/Docks/RemovePort.h
  src/OpenLoco/src/GameCommands/GameCommands.cpp
  src/OpenLoco/src/Localisation/StringIds.h
Labels: pending review

#2426 Add last month production column to the industries list (#1652)
  CHANGELOG.md
  data/language/en-GB.yml
  data/language/nl-NL.yml
  src/OpenLoco/src/Localisation/StringIds.h
  src/OpenLoco/src/Objects/IndustryObject.cpp
  src/OpenLoco/src/Objects/Object.h
  src/OpenLoco/src/Windows/IndustryList.cpp
  src/OpenLoco/src/Windows/IndustryWindow.cpp
Labels: feature, changelog

#2468 Correct naming and use of ViewportVisibility::heightMarksOnTrack
  CHANGELOG.md
  src/OpenLoco/src/Ui/WindowManager.cpp
  src/OpenLoco/src/Ui/WindowManager.h
  src/OpenLoco/src/Windows/Construction/ConstructionTab.cpp
Labels: changelog
